In [1]:
!pip install selenium
!pip install beautifulsoup4

Requirement already satisfied: selenium in c:\users\dines\anaconda3\lib\site-packages (4.2.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dines\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\users\dines\anaconda3\lib\site-packages (from selenium) (1.26.4)
Requirement already satisfied: trio~=0.17 in c:\users\dines\anaconda3\lib\site-packages (from selenium) (0.21.0)
Requirement already satisfied: sortedcontainers in c:\users\dines\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.3.0)
Requirement already satisfied: idna in c:\users\dines\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\dines\anaconda3\lib\site-packages (from trio~=0.17->selenium) (20.3.0)
Requirement already satisfied: outcome in c:\users\dines\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in c:\users\dines\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\dines\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: cffi>=1.14 in c:\users\dines\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.5)
Requirement already satisfied: pycparser in c:\users\dines\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\dines\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\dines\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (20.0.1)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\dines\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (3.4.7)
Requirement already satisfied: certifi in c:\users\dines\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2020.12.5)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\dines\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: six>=1.5.2 in c:\users\dines\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure,socks]~=1.26->selenium) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dines\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)
Requirement already satisfied: beautifulsoup4 in c:\users\dines\anaconda3\lib\site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\dines\anaconda3\lib\site-packages (from beautifulsoup4) (2.2.1)

In [9]:
import selenium
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.

In [3]:
import requests # library to handle requests

In [8]:
# get the response in the form of html
wikiurl="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
table_class="wikitable sortable jquery-tablesorter"
response=requests.get(wikiurl)
print(response.status_code)

200

In [9]:
# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(response.text, 'html.parser')
youtubetable=soup.find('table',{'class':"wikitable"})

In [10]:
youtubetable

<table class="wikitable sortable">
<caption>Top 30 most-viewed YouTube videos<sup class="reference" id="cite_ref-2"><a href="#cite_note-2">[2]</a></sup>
</caption>
<tbody><tr>
<th><abbr title="Number">No.</abbr>
</th>
<th>Video name
</th>
<th>Uploader
</th>
<th>Views (billions)
</th>
<th data-sort-type="usLongDate">Upload date
</th>
<th class="unsortable">Note
</th></tr>
<tr>
<td align="center">1.</td>
<td>"<a class="mw-redirect" href="/wiki/Baby_Shark_Dance" title="Baby Shark Dance">Baby Shark Dance</a>"<sup class="reference" id="cite_ref-Baby_Shark_Dance_3-0"><a href="#cite_note-Baby_Shark_Dance-3">[3]</a></sup></td>
<td><a href="/wiki/Pinkfong" title="Pinkfong">Pinkfong Baby Shark - Kids' Songs &amp; Stories</a></td>
<td align="center">10.92</td>
<td align="right">June 17, 2016</td>
<td align="center"><sup class="reference" id="cite_ref-6"><a href="#cite_note-6">[A]</a></sup>
</td></tr>
<tr>
<td align="center">2.</td>
<td>"<a href="/wiki/Despacito#Music_video" title="Despacito">Despacito</a>"<sup class="reference" id="cite_ref-Despacito_7-0"><a href="#cite_note-Despacito-7">[6]</a></sup></td>
<td><a href="/wiki/Luis_Fonsi" title="Luis Fonsi">Luis Fonsi</a></td>
<td align="center">7.90</td>
<td align="right">January 12, 2017</td>
<td align="center"><sup class="reference" id="cite_ref-despacitoview_13-0"><a href="#cite_note-despacitoview-13">[B]</a></sup>
</td></tr>
<tr>
<td align="center">3.</td>
<td>"<a class="mw-redirect" href="/wiki/Johny_Johny_Yes_Papa#YouTube_videos" title="Johny Johny Yes Papa">Johny Johny Yes Papa</a>"<sup class="reference" id="cite_ref-Johny_Johny_Yes_Papa_14-0"><a href="#cite_note-Johny_Johny_Yes_Papa-14">[12]</a></sup></td>
<td>LooLoo Kids</td>
<td align="center">6.39</td>
<td align="right">October 8, 2016</td>
<td align="center"><sup class="reference" id="cite_ref-15"><a href="#cite_note-15">[C]</a></sup>
</td></tr>
<tr>
<td align="center">4.</td>
<td>"<a href="/wiki/Shape_of_You#Music_video" title="Shape of You">Shape of You</a>"<sup class="reference" id="cite_ref-Shape_of_You_16-0"><a href="#cite_note-Shape_of_You-16">[13]</a></sup></td>
<td><a href="/wiki/Ed_Sheeran" title="Ed Sheeran">Ed Sheeran</a></td>
<td align="center">5.76</td>
<td align="right">January 30, 2017</td>
<td align="center"><sup class="reference" id="cite_ref-18"><a href="#cite_note-18">[D]</a></sup>
</td></tr>
<tr>
<td align="center">5.</td>
<td>"<a href="/wiki/See_You_Again#Music_video" title="See You Again">See You Again</a>"<sup class="reference" id="cite_ref-See_You_Again_19-0"><a href="#cite_note-See_You_Again-19">[15]</a></sup></td>
<td><a href="/wiki/Wiz_Khalifa" title="Wiz Khalifa">Wiz Khalifa</a></td>
<td align="center">5.56</td>
<td align="right">April 6, 2015</td>
<td align="center"><sup class="reference" id="cite_ref-24"><a href="#cite_note-24">[E]</a></sup>
</td></tr>
<tr>
<td align="center">6.</td>
<td>"Bath Song"<sup class="reference" id="cite_ref-Bath_Song_25-0"><a href="#cite_note-Bath_Song-25">[20]</a></sup></td>
<td><a class="mw-redirect" href="/wiki/Cocomelon_%E2%80%93_Nursery_Rhymes" title="Cocomelon – Nursery Rhymes">Cocomelon – Nursery Rhymes</a></td>
<td align="center">5.50</td>
<td align="right">May 2, 2018</td>
<td align="center"><sup class="reference" id="cite_ref-26"><a href="#cite_note-26">[F]</a></sup>
</td></tr>
<tr>
<td align="center">7.</td>
<td>"Phonics Song with Two Words"<sup class="reference" id="cite_ref-Phonics_Song_27-0"><a href="#cite_note-Phonics_Song-27">[21]</a></sup></td>
<td><a href="/wiki/ChuChu_TV" title="ChuChu TV">ChuChu TV</a></td>
<td align="center">4.71</td>
<td align="right">March 6, 2014</td>
<td align="center"><sup class="reference" id="cite_ref-28"><a href="#cite_note-28">[G]</a></sup>
</td></tr>
<tr>
<td align="center">8.</td>
<td>"<a href="/wiki/Uptown_Funk#Music_video" title="Uptown Funk">Uptown Funk</a>"<sup class="reference" id="cite_ref-Uptown_Funk_29-0"><a href="#cite_note-Uptown_Funk-29">[22]</a></sup></td>
<td><a href="/wiki/Mark_Ronson" title="Mark Ronson">Mark Ronson</a></td>
<td align="center">4.62</td>
<td align="right">November 19, 2014</td>
<td align="center"><sup class="reference" id="cite_ref-30"><a href="#cite_note-30">[H]</a></sup>
</td></tr>
<tr>
<td align="center">9.</td>
<td>"Learning Colors – Colorful Eggs on a Farm"<sup class="reference" id="cite_ref-Eggs_31-0"><a href="#cite_note-Eggs-31">[23]</a></sup></td>
<td>Miroshka TV</td>
<td align="center">4.59</td>
<td align="right">February 27, 2018</td>
<td align="center"><sup class="reference" id="cite_ref-32"><a href="#cite_note-32">[I]</a></sup>
</td></tr>
<tr>
<td align="center">10.</td>
<td>"<i><a href="/wiki/Masha_and_the_Bear" title="Masha and the Bear">Masha and the Bear</a></i> – Recipe for Disaster"<sup class="reference" id="cite_ref-Masha_and_the_Bear_33-0"><a href="#cite_note-Masha_and_the_Bear-33">[24]</a></sup></td>
<td>Get Movies</td>
<td align="center">4.50</td>
<td align="right">January 31, 2012</td>
<td align="center"><sup class="reference" id="cite_ref-34"><a href="#cite_note-34">[J]</a></sup>
</td></tr>
<tr>
<td align="center">11.</td>
<td>"<a href="/wiki/Gangnam_Style_(music_video)" title="Gangnam Style (music video)">Gangnam Style</a>"<sup class="reference" id="cite_ref-Gangnam_Style_35-0"><a href="#cite_note-Gangnam_Style-35">[25]</a></sup></td>
<td><a href="/wiki/Psy" title="Psy">Psy</a></td>
<td align="center">4.47</td>
<td align="right">July 15, 2012</td>
<td align="center"><sup class="reference" id="cite_ref-gangnamview_40-0"><a href="#cite_note-gangnamview-40">[K]</a></sup>
</td></tr>
<tr>
<td align="center">12.</td>
<td>"Wheels on the Bus"<sup class="reference" id="cite_ref-41"><a href="#cite_note-41">[30]</a></sup></td>
<td><a class="mw-redirect" href="/wiki/Cocomelon_%E2%80%93_Nursery_Rhymes" title="Cocomelon – Nursery Rhymes">Cocomelon – Nursery Rhymes</a></td>
<td align="center">4.18</td>
<td align="right">May 24, 2018</td>
<td>
</td></tr>
<tr>
<td align="center">13.</td>
<td>"<a href="/wiki/Dame_Tu_Cosita#Music_video" title="Dame Tu Cosita">Dame Tu Cosita</a>"<sup class="reference" id="cite_ref-Dame_Tu_Cosita_42-0"><a href="#cite_note-Dame_Tu_Cosita-42">[31]</a></sup></td>
<td><a href="/wiki/El_Chombo" title="El Chombo">El Chombo</a></td>
<td align="center">3.97</td>
<td align="right">April 5, 2018</td>
<td>
</td></tr>
<tr>
<td align="center">14.</td>
<td>"<a href="/wiki/Sugar_(Maroon_5_song)#Music_video" title="Sugar (Maroon 5 song)">Sugar</a>"<sup class="reference" id="cite_ref-Sugar_43-0"><a href="#cite_note-Sugar-43">[32]</a></sup></td>
<td><a href="/wiki/Maroon_5" title="Maroon 5">Maroon 5</a></td>
<td align="center">3.72</td>
<td align="right">January 14, 2015</td>
<td>
</td></tr>
<tr>
<td align="center">15.</td>
<td>"<a href="/wiki/Roar_(song)#Music_video" title="Roar (song)">Roar</a>"<sup class="reference" id="cite_ref-Roar_44-0"><a href="#cite_note-Roar-44">[33]</a></sup></td>
<td><a href="/wiki/Katy_Perry" title="Katy Perry">Katy Perry</a></td>
<td align="center">3.61</td>
<td align="right">September 5, 2013</td>
<td>
</td></tr>
<tr>
<td align="center">16.</td>
<td>"<a href="/wiki/Counting_Stars#Music_video" title="Counting Stars">Counting Stars</a>"<sup class="reference" id="cite_ref-Counting_Stars_45-0"><a href="#cite_note-Counting_Stars-45">[34]</a></sup></td>
<td><a href="/wiki/OneRepublic" title="OneRepublic">OneRepublic</a></td>
<td align="center">3.60</td>
<td align="right">May 31, 2013</td>
<td>
</td></tr>
<tr>
<td align="center">17.</td>
<td>"<a href="/wiki/Sorry_(Justin_Bieber_song)#Music_videos" title="Sorry (Justin Bieber song)">Sorry</a>"<sup class="reference" id="cite_ref-Sorry_46-0"><a href="#cite_note-Sorry-46">[35]</a></sup></td>
<td><a href="/wiki/Justin_Bieber" title="Justin Bieber">Justin Bieber</a></td>
<td align="center">3.56</td>
<td align="right">October 22, 2015</td>
<td>
</td></tr>
<tr>
<td align="center">18.</td>
<td>"<a href="/wiki/Thinking_Out_Loud#Music_video" title="Thinking Out Loud">Thinking Out Loud</a>"<sup class="reference" id="cite_ref-Thinking_Out_Loud_47-0"><a href="#cite_note-Thinking_Out_Loud-47">[36]</a></sup></td>
<td><a href="/wiki/Ed_Sheeran" title="Ed Sheeran">Ed Sheeran</a></td>
<td align="center">3.47</td>
<td align="right">October 7, 2014</td>
<td>
</td></tr>
<tr>
<td align="center">19.</td>
<td>"<a href="/wiki/Axel_F#Crazy_Frog_version" title="Axel F">Axel F</a>"<sup class="reference" id="cite_ref-48"><a href="#cite_note-48">[37]</a></sup></td>
<td><a href="/wiki/Crazy_Frog" title="Crazy Frog">Crazy Frog</a></td>
<td align="center">3.42</td>
<td align="right">June 16, 2009</td>
<td>
</td></tr>
<tr>
<td align="center">20.</td>
<td>"<a href="/wiki/Girls_Like_You#Music_video" title="Girls Like You">Girls Like You</a>"<sup class="reference" id="cite_ref-Girls_Like_You_49-0"><a href="#cite_note-Girls_Like_You-49">[38]</a></sup></td>
<td><a href="/wiki/Maroon_5" title="Maroon 5">Maroon 5</a></td>
<td align="center">3.31</td>
<td align="right">May 31, 2018</td>
<td>
</td></tr>
<tr>
<td align="center">21.</td>
<td>"<a href="/wiki/Faded_(Alan_Walker_song)#Music_video" title="Faded (Alan Walker song)">Faded</a>"<sup class="reference" id="cite_ref-Faded_50-0"><a href="#cite_note-Faded-50">[39]</a></sup></td>
<td><a class="mw-redirect" href="/wiki/Alan_Walker_(music_producer)" title="Alan Walker (music producer)">Alan Walker</a></td>
<td align="center">3.30</td>
<td align="right">December 3, 2015</td>
<td>
</td></tr>
<tr>
<td align="center">22.</td>
<td>"<a href="/wiki/Dark_Horse_(Katy_Perry_song)#Music_video" title="Dark Horse (Katy Perry song)">Dark Horse</a>"<sup class="reference" id="cite_ref-Dark_Horse_51-0"><a href="#cite_note-Dark_Horse-51">[40]</a></sup></td>
<td><a href="/wiki/Katy_Perry" title="Katy Perry">Katy Perry</a></td>
<td align="center">3.30</td>
<td align="right">February 20, 2014</td>
<td>
</td></tr>
<tr>
<td align="center">23.</td>
<td>"Baa Baa Black Sheep"<sup class="reference" id="cite_ref-52"><a href="#cite_note-52">[41]</a></sup></td>
<td><a class="mw-redirect" href="/wiki/Cocomelon_%E2%80%93_Nursery_Rhymes" title="Cocomelon – Nursery Rhymes">Cocomelon – Nursery Rhymes</a></td>
<td align="center">3.28</td>
<td align="right">June 25, 2018</td>
<td>
</td></tr>
<tr>
<td align="center">24.</td>
<td>"<a href="/wiki/Let_Her_Go#Music_video" title="Let Her Go">Let Her Go</a>"<sup class="reference" id="cite_ref-Let_Her_Go_53-0"><a href="#cite_note-Let_Her_Go-53">[42]</a></sup></td>
<td><a href="/wiki/Passenger_(singer)" title="Passenger (singer)">Passenger</a></td>
<td align="center">3.26</td>
<td align="right">July 25, 2012</td>
<td>
</td></tr>
<tr>
<td align="center">25.</td>
<td>"<a href="/wiki/Bailando_(Enrique_Iglesias_song)#Music_video" title="Bailando (Enrique Iglesias song)">Bailando</a>"<sup class="reference" id="cite_ref-Bailando_54-0"><a href="#cite_note-Bailando-54">[43]</a></sup></td>
<td><a href="/wiki/Enrique_Iglesias" title="Enrique Iglesias">Enrique Iglesias</a></td>
<td align="center">3.23</td>
<td align="right">April 11, 2014</td>
<td>
</td></tr>
<tr>
<td align="center">26.</td>
<td>"<a href="/wiki/Lean_On#Music_video" title="Lean On">Lean On</a>"<sup class="reference" id="cite_ref-Lean_On_55-0"><a href="#cite_note-Lean_On-55">[44]</a></sup></td>
<td><a href="/wiki/Major_Lazer" title="Major Lazer">Major Lazer</a></td>
<td align="center">3.23</td>
<td align="right">March 22, 2015</td>
<td>
</td></tr>
<tr>
<td align="center">27.</td>
<td>"<a href="/wiki/Perfect_(Ed_Sheeran_song)#Music_video" title="Perfect (Ed Sheeran song)">Perfect</a>"<sup class="reference" id="cite_ref-Perfect_56-0"><a href="#cite_note-Perfect-56">[45]</a></sup></td>
<td><a href="/wiki/Ed_Sheeran" title="Ed Sheeran">Ed Sheeran</a></td>
<td align="center">3.20</td>
<td align="right">November 9, 2017</td>
<td>
</td></tr>
<tr>
<td align="center">28.</td>
<td>"<a href="/wiki/Shake_It_Off#Music_video" title="Shake It Off">Shake It Off</a>"<sup class="reference" id="cite_ref-Shake_It_Off_57-0"><a href="#cite_note-Shake_It_Off-57">[46]</a></sup></td>
<td><a href="/wiki/Taylor_Swift" title="Taylor Swift">Taylor Swift</a></td>
<td align="center">3.19</td>
<td align="right">August 18, 2014</td>
<td>
</td></tr>
<tr>
<td align="center">29.</td>
<td>"<a href="/wiki/Waka_Waka_(This_Time_for_Africa)#Music_video" title="Waka Waka (This Time for Africa)">Waka Waka (This Time for Africa)</a>"<sup class="reference" id="cite_ref-Waka_Waka_58-0"><a href="#cite_note-Waka_Waka-58">[47]</a></sup></td>
<td><a href="/wiki/Shakira" title="Shakira">Shakira</a></td>
<td align="center">3.18</td>
<td align="right">June 4, 2010</td>
<td>
</td></tr>
<tr>
<td align="center">30.</td>
<td>"<a href="/wiki/Mi_Gente_(J_Balvin_and_Willy_William_song)#Music_video" title="Mi Gente (J Balvin and Willy William song)">Mi Gente</a>"<sup class="reference" id="cite_ref-Mi_Gente_59-0"><a href="#cite_note-Mi_Gente-59">[48]</a></sup></td>
<td><a href="/wiki/J_Balvin" title="J Balvin">J Balvin</a></td>
<td align="center">3.10</td>
<td align="right">June 29, 2017</td>
<td>
</td></tr>
<tr>
<th colspan="7" style="text-align:center; font-size:8pt;">As of July 8, 2022
</th></tr></tbody></table>

In [11]:
df=pd.read_html(str(youtubetable))
df

[                   No.                                       Video name  \
 0                   1.                            "Baby Shark Dance"[3]
 1                   2.                                   "Despacito"[6]
 2                   3.                       "Johny Johny Yes Papa"[12]
 3                   4.                               "Shape of You"[13]
 4                   5.                              "See You Again"[15]
 5                   6.                                  "Bath Song"[20]
 6                   7.                "Phonics Song with Two Words"[21]
 7                   8.                                "Uptown Funk"[22]
 8                   9.  "Learning Colors – Colorful Eggs on a Farm"[23]
 9                  10.   "Masha and the Bear – Recipe for Disaster"[24]
 10                 11.                              "Gangnam Style"[25]
 11                 12.                          "Wheels on the Bus"[30]
 12                 13.                             "Dame Tu Cosita"[31]
 13                 14.                                      "Sugar"[32]
 14                 15.                                       "Roar"[33]
 15                 16.                             "Counting Stars"[34]
 16                 17.                                      "Sorry"[35]
 17                 18.                          "Thinking Out Loud"[36]
 18                 19.                                     "Axel F"[37]
 19                 20.                             "Girls Like You"[38]
 20                 21.                                      "Faded"[39]
 21                 22.                                 "Dark Horse"[40]
 22                 23.                        "Baa Baa Black Sheep"[41]
 23                 24.                                 "Let Her Go"[42]
 24                 25.                                   "Bailando"[43]
 25                 26.                                    "Lean On"[44]
 26                 27.                                    "Perfect"[45]
 27                 28.                               "Shake It Off"[46]
 28                 29.           "Waka Waka (This Time for Africa)"[47]
 29                 30.                                   "Mi Gente"[48]
 30  As of July 8, 2022                               As of July 8, 2022

                                        Uploader    Views (billions)  \
 0   Pinkfong Baby Shark - Kids' Songs & Stories               10.92
 1                                    Luis Fonsi                7.90
 2                                   LooLoo Kids                6.39
 3                                    Ed Sheeran                5.76
 4                                   Wiz Khalifa                5.56
 5                    Cocomelon – Nursery Rhymes                5.50
 6                                     ChuChu TV                4.71
 7                                   Mark Ronson                4.62
 8                                   Miroshka TV                4.59
 9                                    Get Movies                4.50
 10                                          Psy                4.47
 11                   Cocomelon – Nursery Rhymes                4.18
 12                                    El Chombo                3.97
 13                                     Maroon 5                3.72
 14                                   Katy Perry                3.61
 15                                  OneRepublic                3.60
 16                                Justin Bieber                3.56
 17                                   Ed Sheeran                3.47
 18                                   Crazy Frog                3.42
 19                                     Maroon 5                3.31
 20                                  Alan Walker                3.30
 21                                   Katy Perry                3.30
 22                   Cocomelon – Nursery Rhymes                3.28
 23                                    Passenger                3.26
 24                             Enrique Iglesias                3.23
 25                                  Major Lazer                3.23
 26                                   Ed Sheeran                3.20
 27                                 Taylor Swift                3.19
 28                                      Shakira                3.18
 29                                     J Balvin                3.10
 30                           As of July 8, 2022  As of July 8, 2022

            Upload date                Note          Unnamed: 6
 0        June 17, 2016                 [A]                 NaN
 1     January 12, 2017                 [B]                 NaN
 2      October 8, 2016                 [C]                 NaN
 3     January 30, 2017                 [D]                 NaN
 4        April 6, 2015                 [E]                 NaN
 5          May 2, 2018                 [F]                 NaN
 6        March 6, 2014                 [G]                 NaN
 7    November 19, 2014                 [H]                 NaN
 8    February 27, 2018                 [I]                 NaN
 9     January 31, 2012                 [J]                 NaN
 10       July 15, 2012                 [K]                 NaN
 11        May 24, 2018                 NaN                 NaN
 12       April 5, 2018                 NaN                 NaN
 13    January 14, 2015                 NaN                 NaN
 14   September 5, 2013                 NaN                 NaN
 15        May 31, 2013                 NaN                 NaN
 16    October 22, 2015                 NaN                 NaN
 17     October 7, 2014                 NaN                 NaN
 18       June 16, 2009                 NaN                 NaN
 19        May 31, 2018                 NaN                 NaN
 20    December 3, 2015                 NaN                 NaN
 21   February 20, 2014                 NaN                 NaN
 22       June 25, 2018                 NaN                 NaN
 23       July 25, 2012                 NaN                 NaN
 24      April 11, 2014                 NaN                 NaN
 25      March 22, 2015                 NaN                 NaN
 26    November 9, 2017                 NaN                 NaN
 27     August 18, 2014                 NaN                 NaN
 28        June 4, 2010                 NaN                 NaN
 29       June 29, 2017                 NaN                 NaN
 30  As of July 8, 2022  As of July 8, 2022  As of July 8, 2022  ]

In [12]:
# convert list to dataframe
df=pd.DataFrame(df[0])
df

,No.,Video name,Uploader,Views (billions),Upload date,Note,Unnamed: 6
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,10.92,"June 17, 2016",[A],NaN
1,2.,"""Despacito""[6]",Luis Fonsi,7.90,"January 12, 2017",[B],NaN
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.39,"October 8, 2016",[C],NaN
3,4.,"""Shape of You""[13]",Ed Sheeran,5.76,"January 30, 2017",[D],NaN
4,5.,"""See You Again""[15]",Wiz Khalifa,5.56,"April 6, 2015",[E],NaN
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,5.50,"May 2, 2018",[F],NaN
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,4.71,"March 6, 2014",[G],NaN
7,8.,"""Uptown Funk""[22]",Mark Ronson,4.62,"November 19, 2014",[H],NaN
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,4.59,"February 27, 2018",[I],NaN
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,4.50,"January 31, 2012",[J],NaN
10,11.,"""Gangnam Style""[25]",Psy,4.47,"July 15, 2012",[K],NaN
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,4.18,"May 24, 2018",NaN,NaN
12,13.,"""Dame Tu Cosita""[31]",El Chombo,3.97,"April 5, 2018",NaN,NaN
13,14.,"""Sugar""[32]",Maroon 5,3.72,"January 14, 2015",NaN,NaN
14,15.,"""Roar""[33]",Katy Perry,3.61,"September 5, 2013",NaN,NaN
15,16.,"""Counting Stars""[34]",OneRepublic,3.60,"May 31, 2013",NaN,NaN
16,17.,"""Sorry""[35]",Justin Bieber,3.56,"October 22, 2015",NaN,NaN
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,3.47,"October 7, 2014",NaN,NaN
18,19.,"""Axel F""[37]",Crazy Frog,3.42,"June 16, 2009",NaN,NaN
19,20.,"""Girls Like You""[38]",Maroon 5,3.31,"May 31, 2018",NaN,NaN
20,21.,"""Faded""[39]",Alan Walker,3.30,"December 3, 2015",NaN,NaN
21,22.,"""Dark Horse""[40]",Katy Perry,3.30,"February 20, 2014",NaN,NaN
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,3.28,"June 25, 2018",NaN,NaN
23,24.,"""Let Her Go""[42]",Passenger,3.26,"July 25, 2012",NaN,NaN
24,25.,"""Bailando""[43]",Enrique Iglesias,3.23,"April 11, 2014",NaN,NaN
25,26.,"""Lean On""[44]",Major Lazer,3.23,"March 22, 2015",NaN,NaN
26,27.,"""Perfect""[45]",Ed Sheeran,3.20,"November 9, 2017",NaN,NaN
27,28.,"""Shake It Off""[46]",Taylor Swift,3.19,"August 18, 2014",NaN,NaN
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,3.18,"June 4, 2010",NaN,NaN
29,30.,"""Mi Gente""[48]",J Balvin,3.10,"June 29, 2017",NaN,NaN
30,"As of July 8, 2022","As of July 8, 2022","As of July 8, 2022","As of July 8, 2022","As of July 8, 2022","As of July 8, 2022","As of July 8, 2022"

In [13]:
df.drop(columns=['Note', 'Unnamed: 6'], axis=1, inplace=True)

In [14]:
df.drop(index=30, inplace=True)

In [15]:
df

,No.,Video name,Uploader,Views (billions),Upload date
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,10.92,"June 17, 2016"
1,2.,"""Despacito""[6]",Luis Fonsi,7.90,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.39,"October 8, 2016"
3,4.,"""Shape of You""[13]",Ed Sheeran,5.76,"January 30, 2017"
4,5.,"""See You Again""[15]",Wiz Khalifa,5.56,"April 6, 2015"
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,5.50,"May 2, 2018"
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,4.71,"March 6, 2014"
7,8.,"""Uptown Funk""[22]",Mark Ronson,4.62,"November 19, 2014"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,4.59,"February 27, 2018"
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,4.50,"January 31, 2012"
10,11.,"""Gangnam Style""[25]",Psy,4.47,"July 15, 2012"
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,4.18,"May 24, 2018"
12,13.,"""Dame Tu Cosita""[31]",El Chombo,3.97,"April 5, 2018"
13,14.,"""Sugar""[32]",Maroon 5,3.72,"January 14, 2015"
14,15.,"""Roar""[33]",Katy Perry,3.61,"September 5, 2013"
15,16.,"""Counting Stars""[34]",OneRepublic,3.60,"May 31, 2013"
16,17.,"""Sorry""[35]",Justin Bieber,3.56,"October 22, 2015"
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,3.47,"October 7, 2014"
18,19.,"""Axel F""[37]",Crazy Frog,3.42,"June 16, 2009"
19,20.,"""Girls Like You""[38]",Maroon 5,3.31,"May 31, 2018"
20,21.,"""Faded""[39]",Alan Walker,3.30,"December 3, 2015"
21,22.,"""Dark Horse""[40]",Katy Perry,3.30,"February 20, 2014"
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,3.28,"June 25, 2018"
23,24.,"""Let Her Go""[42]",Passenger,3.26,"July 25, 2012"
24,25.,"""Bailando""[43]",Enrique Iglesias,3.23,"April 11, 2014"
25,26.,"""Lean On""[44]",Major Lazer,3.23,"March 22, 2015"
26,27.,"""Perfect""[45]",Ed Sheeran,3.20,"November 9, 2017"
27,28.,"""Shake It Off""[46]",Taylor Swift,3.19,"August 18, 2014"
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,3.18,"June 4, 2010"
29,30.,"""Mi Gente""[48]",J Balvin,3.10,"June 29, 2017"

# 2. Scrape the details team India’s international fixtures from bcci.tv.

In [16]:
browser = webdriver.Chrome('chromedriver.exe')

In [17]:
browser.get('https://www.bcci.tv/')
browser.maximize_window()
time.sleep(5)

In [18]:
try:
    accept_button = browser.find_element_by_xpath("//button[@class='cookie__accept btn btn-primary']")
    accept_button.click()
except:
    pass

In [19]:
international_button = browser.find_element_by_xpath("//a[@href='https://www.bcci.tv/international/fixtures']")
international_button.click()

In [20]:
time.sleep(5)

In [23]:
fixture_cards = browser.find_elements_by_xpath("//div[@class='fixture-card-top']")
fixture = []
for i in fixture_cards:
    fixture.append(i.text.split('\n'))
fixture

[['INDIA TOUR OF ENGLAND ODI SERIES 2022', '12 JUL 2022', '5:30 PM IST'],
 ['INDIA TOUR OF ENGLAND ODI SERIES 2022', '14 JUL 2022', '5:30 PM IST'],
 ['INDIA TOUR OF ENGLAND ODI SERIES 2022', '17 JUL 2022', '3:30 PM IST'],
 ['INDIA TOUR OF WEST INDIES ODI SERIES 2022', '22 JUL 2022', '7:00 PM IST'],
 ['INDIA TOUR OF WEST INDIES ODI SERIES 2022', '24 JUL 2022', '7:00 PM IST'],
 ['INDIA TOUR OF WEST INDIES ODI SERIES 2022', '27 JUL 2022', '7:00 PM IST']]

In [24]:
series = []
date = []
matchtime = []

for i in fixture:
    series.append(i[0])
    date.append(i[1])
    matchtime.append(i[2])

In [25]:
matches = browser.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
match=[]
for i in matches:
    match.append(i.text.split('\n'))

In [26]:
match

[['1st ODI - Kennington Oval, London'],
 ["2nd ODI - Lord's Cricket Ground, London"],
 ['3rd ODI - Old Trafford, Manchester'],
 ['1st ODI - Queens Park Oval, Trinidad'],
 ['2nd ODI - Queens Park Oval, Trinidad'],
 ['3rd ODI - Queens Park Oval, Trinidad']]

In [27]:
title=[]
location=[]
for i in match:
    if str(i).find('-')!=-1:
        title.append(str(i).split('-')[0])
        location.append(str(i).split('-')[1])
    else:
        title.append('-')
        location.append(i)

In [28]:
for j in range(0,len(title)):
    title[j]=title[j].replace('[','')

In [29]:
bcci = pd.DataFrame()
bcci['Match Title'] = title
bcci['Series'] = series
bcci['Place'] = location
bcci['Date'] = date
bcci['Time'] = matchtime
bcci

,Match Title,Series,Place,Date,Time
0,'1st ODI,INDIA TOUR OF ENGLAND ODI SERIES 2022,"Kennington Oval, London']",12 JUL 2022,5:30 PM IST
1,"""2nd ODI",INDIA TOUR OF ENGLAND ODI SERIES 2022,"Lord's Cricket Ground, London""]",14 JUL 2022,5:30 PM IST
2,'3rd ODI,INDIA TOUR OF ENGLAND ODI SERIES 2022,"Old Trafford, Manchester']",17 JUL 2022,3:30 PM IST
3,'1st ODI,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval, Trinidad']",22 JUL 2022,7:00 PM IST
4,'2nd ODI,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval, Trinidad']",24 JUL 2022,7:00 PM IST
5,'3rd ODI,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval, Trinidad']",27 JUL 2022,7:00 PM IST

In [30]:
browser.close()

# 3. Scrape the details of selenium exception from guru99.com.

In [6]:
browser = webdriver.Chrome('chromedriver.exe')

In [7]:
browser.get('https://www.guru99.com/')
browser.maximize_window()
time.sleep(3)

In [ ]:
selenium_button = browser.find_element_by_xpath("//a[@title='Selenium']")
selenium_button.click()

In [ ]:
exception_button = browser.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")
exception_button.click()

In [ ]:
tables = browser.find_element_by_xpath("//table[@class='table table-striped']")

In [51]:
tables=tables.text.split('\n')[1:]

In [52]:
table=[]
for i in range(len(tables)):
    table.append(tables[i].split(' ')[0])

In [53]:
description=[]
for i in range(len(tables)):
    description.append(tables[i].replace(table[i],''))

In [54]:
exception_selenium = pd.DataFrame()
exception_selenium['Name'] = table
exception_selenium['Description'] = description
exception_selenium

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when a...
1,ElementNotSelectableException,This Selenium exception occurs when an elemen...
2,NoSuchElementException,This Exception occurs if an element could not...
3,NoSuchFrameException,This Exception occurs if the frame target to ...
4,NoAlertPresentException,This Exception occurs when you switch to no p...
5,NoSuchWindowException,This Exception occurs if the window target to...
6,StaleElementReferenceException,This Selenium exception occurs happens when t...
7,SessionNotFoundException,The WebDriver is acting after you quit the br...
8,TimeoutException,Thrown when there is not enough time for a co...
9,WebDriverException,This Exception takes place when the WebDriver...
10,ConnectionClosedException,This type of Exception takes place when there...
11,ElementClickInterceptedException,The command may not be completed as the eleme...
12,ElementNotInteractableException,This Selenium exception is thrown when any el...
13,ErrorInResponseException,This happens while interacting with the Firef...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if...
15,ImeActivationFailedException,This expectation will occur when IME engine a...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certi...
18,InvalidArgumentException,It occurs when an argument does not belong to...
19,InvalidCookieDomainException,This happens when you try to add a cookie und...
20,InvalidCoordinatesException,This type of Exception matches an interacting...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when...
22,InvalidSessionIdException,This Exception took place when the given sess...
23,InvalidSwitchToTargetException,This occurs when the frame or window target t...
24,JavascriptException,This issue occurs while executing JavaScript ...
25,JsonException,It occurs when you afford to get the session ...
26,NoSuchAttributeException,This kind of Exception occurs when the attrib...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the ...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching...
30,NotFoundException,This Exception is a subclass of WebDriverExce...
31,RemoteDriverServerException,This Selenium exception is thrown when the se...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be su...
34,UnableToSetCookieException,This occurs if a driver is unable to set a co...
35,UnexpectedTagNameException,Happens if a support class did not get a web ...
36,UnhandledAlertException,This expectation occurs when there is an aler...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an ...
38,UnknownMethodException,This Exception happens when the requested com...
39,UnreachableBrowserException,This Exception occurs only when the browser i...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t se...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com

In [55]:
browser = webdriver.Chrome('chromedriver.exe')

In [56]:
browser.get('http://statisticstimes.com/')
browser.maximize_window()
time.sleep(3)

In [58]:
economy = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button')
from selenium.webdriver.common.action_chains import ActionChains
a = ActionChains(browser)
a.move_to_element(economy).perform()

In [59]:
india = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]')
india.click()

In [60]:
browser.refresh()

In [62]:
economy = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button')
from selenium.webdriver.common.action_chains import ActionChains
a = ActionChains(browser)
a.move_to_element(economy).perform()
india = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]')
india.click()

In [63]:
states = browser.find_element_by_xpath("//a[@href='india/indian-states-gdp.php']")
states.click()

In [64]:
table = browser.find_element_by_xpath("//div[@id='table_id_wrapper']")

In [65]:
table = table.text.split('\n')[3:-1]

In [66]:
Rank=[]
State=[]
GSDP_19_20=[]
GSDP_18_19=[]
Share=[]
GDP=[]
GSDP201112_19_20=[]
GSDP201112_18_19=[]

In [67]:
for i in range(len(table)):
    Rank.append(str(table[i].split(' ')[0]))
    
    if str(table[i].split(' ')[2]) == '&':
        if str(table[i].split(' ')[4]).isalpha():
            State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3])+' '+str(table[i].split(' ')[4]))
            GSDP_19_20.append(str(table[i].split(' ')[5]))
            GSDP_18_19.append(str(table[i].split(' ')[6]))
            Share.append(str(table[i].split(' ')[7]))
            GDP.append(str(table[i].split(' ')[8]))
            GSDP201112_19_20.append(str(table[i].split(' ')[9]))
            GSDP201112_18_19.append(str(table[i].split(' ')[10]))
        elif str(table[i].split(' ')[3]).isalpha():
            State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3]))
            GSDP_19_20.append(str(table[i].split(' ')[4]))
            GSDP_18_19.append(str(table[i].split(' ')[5]))
            Share.append(str(table[i].split(' ')[6]))
            GDP.append(str(table[i].split(' ')[7]))
            GSDP201112_19_20.append(str(table[i].split(' ')[8]))
            GSDP201112_18_19.append(str(table[i].split(' ')[9]))
        
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha() & str(table[i].split(' ')[3]).isalpha() & str(table[i].split(' ')[4]).isalpha() & str(table[i].split(' ')[5]).isalpha():
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3])+' '+str(table[i].split(' ')[4])+' '+str(table[i].split(' ')[5]))
        GSDP_19_20.append(str(table[i].split(' ')[6]))
        GSDP_18_19.append(str(table[i].split(' ')[7]))
        Share.append(str(table[i].split(' ')[8]))
        GDP.append(str(table[i].split(' ')[9]))
        GSDP201112_19_20.append(str(table[i].split(' ')[10]))
        GSDP201112_18_19.append(str(table[i].split(' ')[11]))
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha() & str(table[i].split(' ')[3]).isalpha() & str(table[i].split(' ')[4]).isalpha():           
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3])+' '+str(table[i].split(' ')[4]))
        GSDP_19_20.append(str(table[i].split(' ')[5]))
        GSDP_19_20.append(str(table[i].split(' ')[6]))
        GSDP_18_19.append(str(table[i].split(' ')[7]))
        Share.append(str(table[i].split(' ')[8]))
        GDP.append(str(table[i].split(' ')[9]))
        GSDP201112_19_20.append(str(table[i].split(' ')[10]))
        GSDP201112_18_19.append(str(table[i].split(' ')[11]))
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha() & str(table[i].split(' ')[3]).isalpha():           
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3]))
        GSDP_19_20.append(str(table[i].split(' ')[4]))
        GSDP_18_19.append(str(table[i].split(' ')[5]))
        Share.append(str(table[i].split(' ')[6]))
        GDP.append(str(table[i].split(' ')[7]))
        GSDP201112_19_20.append(str(table[i].split(' ')[8]))
        GSDP201112_18_19.append(str(table[i].split(' ')[9]))
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha():
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2]))
        GSDP_19_20.append(str(table[i].split(' ')[3]))
        GSDP_18_19.append(str(table[i].split(' ')[4]))
        Share.append(str(table[i].split(' ')[5]))
        GDP.append(str(table[i].split(' ')[6]))
        GSDP201112_19_20.append(str(table[i].split(' ')[7]))
        GSDP201112_18_19.append(str(table[i].split(' ')[8]))
    elif str(table[i].split(' ')[1]).isalpha():
        State.append(str(table[i].split(' ')[1]))
        GSDP_19_20.append(str(table[i].split(' ')[2]))
        GSDP_18_19.append(str(table[i].split(' ')[3]))
        Share.append(str(table[i].split(' ')[4]))
        GDP.append(str(table[i].split(' ')[5]))
        GSDP201112_19_20.append(str(table[i].split(' ')[6]))
        GSDP201112_18_19.append(str(table[i].split(' ')[7]))

In [68]:
GSDP_19_20

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [69]:
print(len(Rank))
print(len(State))
print(len(GSDP_19_20))
print(len(GSDP_18_19))
print(len(Share))
print(len(GDP))
print(len(GSDP201112_19_20))
print(len(GSDP201112_18_19))

33
33
33
33
33
33
33
33

In [70]:
GSDP=pd.DataFrame()
GSDP['Rank'] = Rank
GSDP['State'] = State
GSDP['GSDP (Cr INR at Current prices) 19-20'] = GSDP_19_20
GSDP['GSDP (Cr INR at Current prices) 18-19'] = GSDP_18_19
GSDP['Share'] = Share
GSDP['GDP'] = GDP
GSDP['GSDP (Cr INR at 2011-12 prices) 19-20'] = GSDP201112_19_20
GSDP['GSDP (Cr INR at 2011-12 prices) 18-19'] = GSDP201112_18_19
GSDP

,Rank,State,GSDP (Cr INR at Current prices) 19-20,GSDP (Cr INR at Current prices) 18-19,Share,GDP,GSDP (Cr INR at 2011-12 prices) 19-20,GSDP (Cr INR at 2011-12 prices) 18-19
0,1,Maharashtra,-,"2,632,792",13.94%,399.921,-,"2,039,074"
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629,"1,312,929","1,215,307"
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726,"1,166,817","1,123,982"
3,4,Gujarat,-,"1,502,899",7.96%,228.290,-,"1,186,379"
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806,"1,156,039","1,091,077"
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556,"793,223","739,525"
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179,"711,627","677,428"
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083,"672,018","621,301"
8,9,Telangana,"969,604","861,031",4.56%,130.791,"663,258","612,828"
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977,"561,801","522,009"
10,11,Kerala,-,"781,653",4.14%,118.733,-,"559,412"
11,12,Delhi,"856,112","774,870",4.10%,117.703,"634,408","590,569"
12,13,Haryana,"831,610","734,163",3.89%,111.519,"572,240","531,085"
13,14,Bihar,"611,804","530,363",2.81%,80.562,"414,977","375,651"
14,15,Punjab,"574,760","526,376",2.79%,79.957,"418,868","397,669"
15,16,Odisha,"521,275","487,805",2.58%,74.098,"396,499","376,877"
16,17,Assam,-,"315,881",1.67%,47.982,-,"234,048"
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187,"243,477","231,182"
18,19,Jharkhand,"328,598","297,204",1.57%,45.145,"240,036","224,986"
19,20,Uttarakhand,-,"245,895",1.30%,37.351,-,"193,273"
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690,-,"112,755"
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369,"124,403","117,851"
22,23,Goa,"80,449","73,170",0.39%,11.115,"63,408","57,787"
23,24,Tripura,"55,984","49,845",0.26%,7.571,"40,583","36,963"
24,25,Chandigarh,-,"42,114",0.22%,6.397,-,"31,192"
25,26,Puducherry,"38,253","34,433",0.18%,5.230,"25,093","23,013"
26,27,Meghalaya,"36,572","33,481",0.18%,5.086,"26,695","24,682"
27,28,Sikkim,"32,496","28,723",0.15%,4.363,"20,017","18,722"
28,29,Manipur,"31,790","27,870",0.15%,4.233,"20,673","19,300"
29,30,Nagaland,-,"27,283",0.14%,4.144,-,"17,647"
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737,-,"16,676"
31,32,Mizoram,"26,503","22,287",0.12%,3.385,"18,797","16,478"
32,33,Andaman & Nicobar Islands,-,-,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.

In [77]:
browser = webdriver.Chrome('chromedriver.exe')

In [78]:
browser.get('https://github.com/')
browser.maximize_window()
time.sleep(3)

In [ ]:
time.sleep(2)
explore = browser.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]')
from selenium.webdriver.common.action_chains import ActionChains
a = ActionChains(browser)
a.move_to_element(explore).perform()
trending = browser.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
trending.click()

In [80]:
articles = browser.find_elements_by_xpath("//article[@class='Box-row']")

In [81]:
article=[]
title=[]
description=[]
for i in articles:
    title.append(i.text.split('\n')[0])
    description.append(i.text.split('\n')[1])
    article.append(i.text.split('\n')[2])

In [82]:
for i in range(len(article)):
    article[i] = str(article[i]).split(' ')[0]

In [83]:
for i in range(len(article)):
    if str(article[i]).isalpha() or str(article[i]) =='C#' :
        article[i] = article[i]
    else:
        article[i] = '-'

In [84]:
github = pd.DataFrame()
github['Repository Title']=title
github['Repository Description']=description
github['Language Used']=article
github

,Repository Title,Repository Description,Language Used
0,Sponsor,Star,EbookFoundation
1,Star,facundoolano / software-papers,-
2,Star,PoaceaeTriticum / Exposure_HongSenlian,A
3,Star,PlayCover / PlayCover,Community
4,Star,microsoft / ML-For-Beginners,-
5,Star,gz-yami / mall4cloud,-
6,Star,pocketbase / pocketbase,Open
7,Star,cmhungsteve / Awesome-Transformer-Attention,An
8,Star,renovatebot / renovate,Universal
9,Star,codecrafters-io / build-your-own-x,Master
10,Star,h5bp / Front-end-Developer-Interview-Questions,A
11,Star,jcubic / wayne,Service
12,Star,unifyai / ivy,The
13,Sponsor,Star,-
14,Star,romainthomas / the-poor-mans-obfuscator,Binary
15,Star,microsoft / vscode,Visual
16,Star,tiltedphoques / TiltedEvolution,Skyrim
17,Star,WongKinYiu / yolov7,Implementation
18,Star,apache / arrow,Apache
19,Star,Shopify / sarama,Sarama
20,Star,MicrosoftDocs / azure-docs,Open
21,Star,pittcsc / Summer2023-Internships,Collection
22,Star,sunface / rust-by-practice,Learning
23,Star,ethereum / solidity,-
24,Star,coder / coder,Remote

# 6. Scrape the details of top 100 songs on billiboard.com.

In [26]:
browser = webdriver.Chrome('chromedriver.exe')

In [27]:
browser.get('https:/www.billboard.com/')
browser.maximize_window()

In [31]:
charts = browser.find_element_by_xpath("//a[@class='c-link  lrv-a-unstyle-link lrv-a-unstyle-link lrv-u-color-brand-accent-blue:hover lrv-a-hover-effect lrv-u-whitespace-nowrap lrv-u-color-grey-lightest ']")
charts.click()

In [ ]:
hot = browser.find_element_by_xpath("//a[@class='c-label__link lrv-u-color-brand-primary u-color-black@mobile-max a-font-primary-bold lrv-u-font-size-32 u-whitespace-nowrap@tablet']")
hot.click()

In [45]:
ranks= browser.find_elements_by_xpath("//li[@class='o-chart-results-list__item // lrv-u-background-color-black lrv-u-color-white u-width-100 u-width-55@mobile-max u-width-55@tablet-only lrv-u-height-100p lrv-u-flex lrv-u-flex-direction-column@mobile-max lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey']")
rank=[]
for i in ranks:
    rank.append(i.text)

In [46]:
song=[]
firstsong = browser.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']")
song.append(firstsong[0].text)

In [47]:
songs = browser.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
for i in songs:
    song.append(i.text)

In [48]:
artist=[]
firstartists = browser.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']")
artist.append(firstartists[0].text)

In [49]:
artists = browser.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
for i in artists:
    artist.append(i.text)

In [54]:
lastweek=[]
peak_rank=[]
week=[]

In [62]:
lastweek_1= browser.find_elements_by_xpath("//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")

In [63]:
lastweek.append(lastweek_1[0].text)
peak_rank.append(lastweek_1[1].text)
week.append(lastweek_1[2].text)

In [64]:
lastweek_all= browser.find_elements_by_xpath("//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")

In [65]:
config=[]
for i in lastweek_all:
    config.append(i.text)

In [66]:
temp_lastweek=config[0::6]
for i in temp_lastweek:
    lastweek.append(i)

In [67]:
temp_peakrank=config[1::6]
for i in temp_peakrank:
    peak_rank.append(i)

In [68]:
temp_week=config[2::6]
for i in temp_week:
    week.append(i)

In [69]:
hot_100=pd.DataFrame()
hot_100['Rank']= rank
hot_100['Song Name']=song
hot_100['Artist Name']=artist
hot_100['Last Week Rank']=lastweek
hot_100['Peak Rank']=peak_rank
hot_100['Weeks On Board']=week
hot_100

,Rank,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks On Board
0,1,As It Was,Harry Styles,1,1,14
1,2,About Damn Time,Lizzo,3,2,12
2,3,First Class,Jack Harlow,2,1,13
3,4,Running Up That Hill (A Deal With God),Kate Bush,6,4,26
4,5,Wait For U,Future Featuring Drake & Tems,4,1,10
...,...,...,...,...,...,...
95,96,Best Thing Since Backroads,Jake Owen,-,96,1
96,97,U-Digg,"Lil Baby, 42 Dugg & Veeze",82,52,3
97,98,Unstoppable,Sia,-,98,1
98,99,Rich Minion,Yeat,-,99,1
99,100,Bad Habit,Steve Lacy,-,100,1

# 7. Scrape the details of Data science recruiters from naukri.com.

In [24]:
browser = webdriver.Chrome('chromedriver.exe')

In [25]:
browser.get('https://www.naukri.com/recruiters')
browser.maximize_window()

In [26]:
designation = browser.find_element_by_xpath("//input[@placeholder='Skills, Designations, Companies']")
designation.send_keys("Data Scientist")

In [28]:
search_button = browser.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")
search_button.click()

In [29]:
name=[]
designation=[]
company=[]
skill=[]
loc=[]

In [30]:
rec_names = browser.find_elements_by_xpath("//span[@class='fl ellipsis']")
for i in rec_names:
    name.append(i.text)

In [31]:
rec_desig = browser.find_elements_by_xpath("//span[@class='ellipsis clr']")
for i in rec_desig:
    designation.append(i.text)

In [32]:
rec_temp = browser.find_elements_by_xpath("//a[@class='ellipsis']")

In [33]:
temp_cell=[]
for i in rec_temp:
    temp_cell.append(i.text)
company=temp_cell[1::2]

In [34]:
rec_skill = browser.find_elements_by_xpath("//div[@class='hireSec highlightable']")
for i in rec_skill:
    skill.append(i.text)

In [35]:
rec_loc = browser.find_elements_by_xpath("//small[@class='ellipsis']")
counter=0
for i in rec_loc:
    if counter==35:
        loc.append('-')
        counter+=1
        loc.append(i.text)
    else:
        loc.append(i.text)
        counter+=1

In [36]:
naukri=pd.DataFrame()
naukri['Name']=name
naukri['Designation']=designation
naukri['Company']=company
naukri['Skills they hire for']=skill
naukri['Location']=loc
naukri

,Name,Designation,Company,Skills they hire for,Location
0,Tanushree,Lead Recruiter,RecRoots,"UI Developers, Software Engineers, Quality Ass...",Noida
1,sashi bhushan,Senior Specialist,Wipro,"pig, hbase, sas, spss, apache, python, nosql, ...",Bengaluru / Bangalore
2,Bitapi,HR and Operation Manager,Anvaya,"Hadoop, Big Data, Data Scientists, Java, Sprin...",Bengaluru / Bangalore
3,Gajendra Singh,Head of Recruitment - Product &amp;...,A Leading of Product Start-UP Company,"Data Scientist, Big Data, Hadoop, Web Analytic...",Noida
4,Sadashiv Kulkarni,Company HR,Digitially Insights Pvt Ltd,"Big Data Engineer, Data Scientist, Solutions, ...",Pune
5,Invelopment,Company HR,Invelopment,Scandinavian Startups,Ahmedabad
6,Anjali Srivastava,Director HR,CodeFire Technologies Pvt. Ltd.,"Technical, Business Development Executive, Sof...",Noida
7,Helly Vyas,HR Business Partner,AM - TA &amp; HR,"Big Data technology, PLSQL, Web Developer, Jav...",Pune
8,Ashish Verma,Senior Associate Human Resources,Evalueserve.com Private Limited,"SAS, VBA, Business Information Services(BIS), ...",Gurgaon
9,Balaji Prabhakaran,Company Recruiter,Oportun,"Technical Solution Architect, Data Scientist, ...",Chennai
10,Shiva Kumar N,Founder,Rapid Talent Solutions -9148242334,"salaesforce, Web Technologies, .net, .net full...",Bengaluru / Bangalore
11,Bhuwneshari Devi,Lead Talent Acquisition,Success Pact Consulting,"Amazon, Olacabs, Quikr, Bankbazzar, Uber, Flip...",Delhi
12,HS Sandesh,Talent Evangelist www staffiohr co,Staffio HR,"Digital Marketing, General Manager, Business D...",Bengaluru / Bangalore
13,Anoop Somarajan,Manager - Talent Acquisition,R1RCM,"Asp.net, Hl7, Mirth, Perl, Xamarin, Javascript...",Chennai
14,Datafoundry,Company HR,JAITRA SOFTWARE SOLUTIONS PVT LTD,"Webmethods Developer, Mean Stack, Business Ana...",Bengaluru / Bangalore
15,A Valsa Florina,Recruitment Specialist,Redbus.in,"Business Analyst, Front end developer, legal, ...",Bengaluru / Bangalore
16,Kalaivani M V,HR Manager,ZYUDLY LABS DATA SOLUTIONS PRIVATE LIMITED,"Data Scientist, Cloud Computing, Mobile Applic...",Chennai
17,Prashant K,Sr HR,Confidential,"Data Analyst, Statistical Analysis, Data Scien...",Bengaluru / Bangalore
18,Radhika,HR Associate,Bright Bridge Info-tech Pvt Ltd,"business analyst - IT (python), pay per click,...",Coimbatore
19,Rakhi,HR recruiter,Constalytics,"Data Scientist, Data Research Analyst, Big Dat...",Singapore - (singapore)
20,Shefali Gupta,Recruitment Consultant,HUNTINGCUBE RECRUITMENT SOLUTIONS PRIVATE...,"Java, Python, Ror, Nodejs, React.js, Angularjs...",Noida
21,Monika Jain,Talent Aquistion Lead,Info Edge India Limited,"Lamp Developer, Ui/ux Developer, Qa Engineer, ...",Noida
22,Trilok Nath,Senior IT Recruiter,Molveno Consulting Private Limited,".Net Developers With Angular Js, Html, Front E...",Hyderabad / Secunderabad
23,Rashmi Kathuria,Talent Acquisition Specialist (Specialized...,Mount Talent consulting,"Leading MNCs, Product based organizations",Noida
24,Vidya Rani Hadimani,Business Manager Delivery,Talent Management Labs Inc.,Amazon Walmart Adobe OLA Myntracom Komli Media...,Bengaluru / Bangalore
25,Monika Singh Thakur,Technical Recruiter,ValueLabs,"Big Data Analytics, Marketing Analytics, Full ...",Indore
26,Shikha Bakshi,Senior Manager Recruitment,Fractal Analytics!!,"Analytics, Big Data, Hadoop, Python",Gurgaon
27,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
28,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
29,Ravi,Team HR,Einfluss Teknocommercial Pvt. Ltd.,"Deep Learning, Machine Learning, unstructured ...",Ghaziabad
30,Sai Siddharth Chinta,Technical Recruiter,McKinsey &amp; Company,Not Specified,Bengaluru / Bangalore
31,Ishu Kumar,Co Founder &amp; Ceo,Data X,"Python, Machine Learning, Sql, Data Science",Bengaluru / Bangalore
32,Vivek Shrivastava,Assistant Manager Human Resources,InnovAccer Management Pvt Ltd,"Business Analyst, analytics, Decesion Scientis...",Noida
33,Gayathri E,Sr Recruitment,Wonderwrks IT Services Private Limited,"IT Infrastructure Management, PHP, Wordpress, ...",Chennai
34,Best In Town Analytics,Analytics Associate,BITA,Data Analytics,Bengaluru / Bangalore
35,Santhosh Nagaiah,Chief marketing officer,Tuple Technologies Pte Ltd,"Data Science, Project Management, Backend",-
36,priyanka,General Manager,Reliance Industries,"Sap, Saas, Sql, Hadoop, Production Planning, B...",Mumbai
37,Nagendla Syam Kumar,Data Scientist,FLOWERHORN IT PVT LTD,"Machine Learning, NLP, Performance Review, HR,...",Bengaluru / Bangalore
38,Renny Benita K,Operations Manager,DeepIQ Software Solutions Pvt Ltd,"Core Java, J2ee, Big Data, Machine Learning, D...",Bengaluru / Bangalore
39,Jamil Akhtar,Company Recruiter,Quikkloan,Not Specified,Delhi
40,Roshan Menugu,Company Recruiter,Cyient Limited,Not Specified,Hyderabad / Secunderabad
41,Sudipta Samanta,Founder,DataNnoviteSol LLP,Not Specified,Pune
42,HR Team,Company HR,Terra Blue Exploration Technologies Pvt....,Not Specified,Bengaluru / Bangalore
43,rajesh,HR Executive,quantum value IT services,"Data Scientist, Tableau, R Tool, Data Analytic...",Bengaluru / Bangalore
44,navya neluri,Data Scientist,asens labs,Not Specified,Hyderabad / Secunderabad
45,Ram Kumar,Data Scientist,Working As A Freelancer,Not Specified,Pune
46,Shreya Naithani,Talent Acquisition Executive,Purplejack Labs Pvt. Ltd.,"Node.js, React.js, Etl Testing, Data Warehousi...",Mumbai
47,Vanitha Senkurichi,Company HR,Quaero 3 India Ltd,"sql, Ui Development, ssis, Data Modeling, Data...",Bengaluru / Bangalore
48,Sravan Kumar Ranga,Assistant Manager,GSPANN Technologies,"devops, build and release, Delivery Manager, O...",Hyderabad / Secunderabad
49,Zack,Recruitment Manager,Perex Engineering Pvt Ltd,"Software Development, Javascript, Core Java, J...",Hyderabad / Secunderabad

In [37]:
browser.close()

# 8. Scrape the details of Highest selling novels.

In [70]:
browser = webdriver.Chrome('chromedriver.exe')

In [71]:
browser.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
browser.maximize_window()

In [72]:
table = browser.find_element_by_xpath("//table[@class='in-article sortable']")

In [73]:
Book_name =[]
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

In [ ]:
temp_Book_name = browser.find_elements_by_xpath("//span[@class='genre']")
Book_name=[]
for i in temp_genres:
    genre.append(i.text)

# 9. Scrape the details most watched tv series of all time from imdb.com.

In [12]:
browser = webdriver.Chrome('chromedriver.exe')

In [13]:
browser.get('https://www.imdb.com/list/ls095964455/')
browser.maximize_window()

In [14]:
temp_titles = browser.find_elements_by_xpath("//h3[@class='lister-item-header']")
headers=[]
for i in temp_titles:
    headers.append(i.text.replace('\n',''))

In [15]:
x=[]
for i in range(len(headers)):
    x.append(headers[i].split('.')[1])

In [16]:
name=[]
year=[]
for i in range(len(x)):
    if x[i]==' Mr':
        name.append(' Mr.Robot')
        year.append('2015-2019')
    elif x[i]==' Agents of S':
        name.append(' Agents of S.H.I.E.L.D')
        year.append('2013-2020')
    else:
        name.append(x[i].split('(')[0])
        year.append(x[i].split('(')[1].replace(')',''))

In [17]:
temp_genres = browser.find_elements_by_xpath("//span[@class='genre']")
genre=[]
for i in temp_genres:
    genre.append(i.text)

In [18]:
temp_runtime = browser.find_elements_by_xpath("//span[@class='runtime']")
runtime=[]
for i in temp_runtime:
    runtime.append(i.text)

In [19]:
temp_rating = browser.find_elements_by_xpath("//div[@class='ipl-rating-star small']")
rating=[]
for i in temp_rating:
    rating.append(i.text.replace('\n',''))

In [20]:
temp_vote = browser.find_elements_by_xpath("//span[@name='nv']")
vote=[]
for i in temp_vote:
    vote.append(i.text.replace('\n',''))

In [21]:
imdb = pd.DataFrame()
imdb['Name']=name
imdb['Year Span']=year
imdb['Genre']=genre
imdb['Runtime']=runtime
imdb['Ratings']=rating
imdb['Votes']=vote
imdb

,Name,Year Span,Genre,Runtime,Ratings,Votes
0,Game of Thrones,2011–2019,"Action, Adventure, Drama",57 min,9.2,"2,009,421"
1,Stranger Things,2016–,"Drama, Fantasy, Horror",51 min,8.7,"1,090,467"
2,The Walking Dead,2010–2022,"Drama, Horror, Thriller",44 min,8.2,"955,141"
3,13 Reasons Why,2017–2020,"Drama, Mystery, Thriller",60 min,7.5,"285,545"
4,The 100,2014–2020,"Drama, Mystery, Sci-Fi",43 min,7.6,"245,203"
...,...,...,...,...,...,...
95,Reign,2013–2017,Drama,42 min,7.4,"49,097"
96,A Series of Unfortunate Events,2017–2019,"Adventure, Comedy, Drama",50 min,7.8,"59,894"
97,Criminal Minds,2005–2020,"Crime, Drama, Mystery",42 min,8.1,"192,247"
98,Scream: The TV Series,2015–2019,"Comedy, Crime, Drama",45 min,7.1,"40,596"
99,The Haunting of Hill House,2018,"Drama, Horror, Mystery",572 min,8.6,"231,249"

In [22]:
browser.close()

# 10. Details of Datasets from UCI machine learning repositories.

In [3]:
browser = webdriver.Chrome('chromedriver.exe')

In [4]:
browser.get('https://archive.ics.uci.edu/')
browser.maximize_window()

In [5]:
dataset_button = browser.find_element_by_xpath("//a[@href='datasets.php']")
dataset_button.click()

In [6]:
temp_titles = browser.find_elements_by_xpath("//table[@border='1']")
headers=[]
headers = temp_titles[0].text.split('\n')

In [7]:
temp_titles[0].text

"Name\nData Types\nDefault Task\nAttribute Types\n# Instances\n# Attributes\nYear\n  Abalone\nMultivariate \nClassification \nCategorical, Integer, Real \n4177 \n8 \n1995 \n  Adult\nMultivariate \nClassification \nCategorical, Integer \n48842 \n14 \n1996 \n  Annealing\nMultivariate \nClassification \nCategorical, Integer, Real \n798 \n38 \n    Anonymous Microsoft Web Data\n  Recommender-Systems \nCategorical \n37711 \n294 \n1998 \n  Arrhythmia\nMultivariate \nClassification \nCategorical, Integer, Real \n452 \n279 \n1998 \n  Artificial Characters\nMultivariate \nClassification \nCategorical, Integer, Real \n6000 \n7 \n1992 \n  Audiology (Original)\nMultivariate \nClassification \nCategorical \n226 \n  1987 \n  Audiology (Standardized)\nMultivariate \nClassification \nCategorical \n226 \n69 \n1992 \n  Auto MPG\nMultivariate \nRegression \nCategorical, Real \n398 \n8 \n1993 \n  Automobile\nMultivariate \nRegression \nCategorical, Integer, Real \n205 \n26 \n1987 \n  Badges\nUnivariate, Text \nClassification \n  294 \n1 \n1994 \n  Balance Scale\nMultivariate \nClassification \nCategorical \n625 \n4 \n1994 \n  Balloons\nMultivariate \nClassification \nCategorical \n16 \n4 \n    Breast Cancer\nMultivariate \nClassification \nCategorical \n286 \n9 \n1988 \n  Breast Cancer Wisconsin (Original)\nMultivariate \nClassification \nInteger \n699 \n10 \n1992 \n  Breast Cancer Wisconsin (Prognostic)\nMultivariate \nClassification, Regression \nReal \n198 \n34 \n1995 \n  Breast Cancer Wisconsin (Diagnostic)\nMultivariate \nClassification \nReal \n569 \n32 \n1995 \n  Pittsburgh Bridges\nMultivariate \nClassification \nCategorical, Integer \n108 \n13 \n1990 \n  Car Evaluation\nMultivariate \nClassification \nCategorical \n1728 \n6 \n1997 \n  Census Income\nMultivariate \nClassification \nCategorical, Integer \n48842 \n14 \n1996 \n  Chess (King-Rook vs. King-Knight)\nMultivariate, Data-Generator \nClassification \nCategorical, Integer \n  22 \n1988 \n  Chess (King-Rook vs. King-Pawn)\nMultivariate \nClassification \nCategorical \n3196 \n36 \n1989 \n  Chess (King-Rook vs. King)\nMultivariate \nClassification \nCategorical, Integer \n28056 \n6 \n1994 \n  Chess (Domain Theories)\nDomain-Theory \n            Bach Chorales\nUnivariate, Time-Series \n  Categorical, Integer \n100 \n6 \n    Connect-4\nMultivariate, Spatial \nClassification \nCategorical \n67557 \n42 \n1995 \n  Credit Approval\nMultivariate \nClassification \nCategorical, Integer, Real \n690 \n15 \n    Japanese Credit Screening\nMultivariate, Domain-Theory \nClassification \nCategorical, Real, Integer \n125 \n  1992 \n  Computer Hardware\nMultivariate \nRegression \nInteger \n209 \n9 \n1987 \n  Contraceptive Method Choice\nMultivariate \nClassification \nCategorical, Integer \n1473 \n9 \n1997 \n  Covertype\nMultivariate \nClassification \nCategorical, Integer \n581012 \n54 \n1998 \n  Cylinder Bands\nMultivariate \nClassification \nCategorical, Integer, Real \n512 \n39 \n1995 \n  Dermatology\nMultivariate \nClassification \nCategorical, Integer \n366 \n33 \n1998 \n  Diabetes\nMultivariate, Time-Series \n  Categorical, Integer \n  20 \n    DGP2 - The Second Data Generation Program\nData-Generator \n  Real \n        Document Understanding\n          1994 \n  EBL Domain Theories\n              Echocardiogram\nMultivariate \nClassification \nCategorical, Integer, Real \n132 \n12 \n1989 \n  Ecoli\nMultivariate \nClassification \nReal \n336 \n8 \n1996 \n  Flags\nMultivariate \nClassification \nCategorical, Integer \n194 \n30 \n1990 \n  Function Finding\n  Function-Learning \nReal \n352 \n  1990 \n  Glass Identification\nMultivariate \nClassification \nReal \n214 \n10 \n1987 \n  Haberman's Survival\nMultivariate \nClassification \nInteger \n306 \n3 \n1999 \n  Hayes-Roth\nMultivariate \nClassification \nCategorical \n160 \n5 \n1989 \n  Heart Disease\nMultivariate \nClassification \nCategorical, Integer, Real \n303 \n75 \n1988 \n  Hepatitis\nMultivariate \nClassification \nCategorical, Integer, Real \n155 \n19 \n1988 \n  Horse Colic\nMultivariate \nClassification \nCategorical, Integer, Real \n368 \n27 \n1989 \n  ICU\nMultivariate, Time-Series \n  Real \n        Image Segmentation\nMultivariate \nClassification \nReal \n2310 \n19 \n1990 \n  Internet Advertisements\nMultivariate \nClassification \nCategorical, Integer, Real \n3279 \n1558 \n1998 \n  Ionosphere\nMultivariate \nClassification \nInteger, Real \n351 \n34 \n1989 \n  Iris\nMultivariate \nClassification \nReal \n150 \n4 \n1988 \n  ISOLET\nMultivariate \nClassification \nReal \n7797 \n617 \n1994 \n  Kinship\nRelational \nRelational-Learning \nCategorical \n104 \n12 \n1990 \n  Labor Relations\nMultivariate \n  Categorical, Integer, Real \n57 \n16 \n1988 \n  LED Display Domain\nMultivariate, Data-Generator \nClassification \nCategorical \n  7 \n1988 \n  Lenses\nMultivariate \nClassification \nCategorical \n24 \n4 \n1990 \n  Letter Recognition\nMultivariate \nClassification \nInteger \n20000 \n16 \n1991 \n  Liver Disorders\nMultivariate \n  Categorical, Integer, Real \n345 \n7 \n1990 \n  Logic Theorist\nDomain-Theory \n            Lung Cancer\nMultivariate \nClassification \nInteger \n32 \n56 \n1992 \n  Lymphography\nMultivariate \nClassification \nCategorical \n148 \n18 \n1988 \n  Mechanical Analysis\nMultivariate \nClassification \nCategorical, Integer, Real \n209 \n8 \n1990 \n  Meta-data\nMultivariate \nClassification \nCategorical, Integer, Real \n528 \n22 \n1996 \n  Mobile Robots\nDomain-Theory \n  Categorical, Integer, Real \n    1995 \n  Molecular Biology (Promoter Gene Sequences)\nSequential, Domain-Theory \nClassification \nCategorical \n106 \n58 \n1990 \n  Molecular Biology (Protein Secondary Structure)\nSequential \nClassification \nCategorical \n128 \n      Molecular Biology (Splice-junction Gene Sequences)\nSequential, Domain-Theory \nClassification \nCategorical \n3190 \n61 \n1992 \n  MONK's Problems\nMultivariate \nClassification \nCategorical \n432 \n7 \n1992 \n  Moral Reasoner\nDomain-Theory \n    202 \n  1994 \n  Multiple Features\nMultivariate \nClassification \nInteger, Real \n2000 \n649 \n    Mushroom\nMultivariate \nClassification \nCategorical \n8124 \n22 \n1987 \n  Musk (Version 1)\nMultivariate \nClassification \nInteger \n476 \n168 \n1994 \n  Musk (Version 2)\nMultivariate \nClassification \nInteger \n6598 \n168 \n1994 \n  Nursery\nMultivariate \nClassification \nCategorical \n12960 \n8 \n1997 \n  Othello Domain Theory\nDomain-Theory \n        1991 \n  Page Blocks Classification\nMultivariate \nClassification \nInteger, Real \n5473 \n10 \n1995 \n  Optical Recognition of Handwritten Digits\nMultivariate \nClassification \nInteger \n5620 \n64 \n1998 \n  Pen-Based Recognition of Handwritten Digits\nMultivariate \nClassification \nInteger \n10992 \n16 \n1998 \n  Post-Operative Patient\nMultivariate \nClassification \nCategorical, Integer \n90 \n8 \n1993 \n  Primary Tumor\nMultivariate \nClassification \nCategorical \n339 \n17 \n1988 \n  Prodigy\nDomain-Theory \n            Qualitative Structure Activity Relationships\nDomain-Theory \n            Quadruped Mammals\nMultivariate, Data-Generator \nClassification \nReal \n  72 \n1992 \n  Servo\nMultivariate \nRegression \nCategorical, Integer \n167 \n4 \n1993 \n  Shuttle Landing Control\nMultivariate \nClassification \nCategorical \n15 \n6 \n1988 \n  Solar Flare\nMultivariate \nRegression \nCategorical \n1389 \n10 \n1989 \n  Soybean (Large)\nMultivariate \nClassification \nCategorical \n307 \n35 \n1988 \n  Soybean (Small)\nMultivariate \nClassification \nCategorical \n47 \n35 \n1987 \n  Challenger USA Space Shuttle O-Ring\nMultivariate \nRegression \nInteger \n23 \n4 \n1993 \n  Low Resolution Spectrometer\nMultivariate \nClassification \nInteger, Real \n531 \n102 \n1988 \n  Spambase\nMultivariate \nClassification \nInteger, Real \n4601 \n57 \n1999 \n  SPECT Heart\nMultivariate \nClassification \nCategorical \n267 \n22 \n2001 \n  SPECTF Heart\nMultivariate \nClassification \nInteger \n267 \n44 \n2001 \n  Sponge\nMultivariate \nClustering \nCategorical, Integer \n76 \n45 \n    Statlog Project\n          1992 \n  Student Loan Relational\nDomain-Theory \n    1000 \n  1993 \n  Teaching Assistant Evaluation\nMultivariate \nClassification \nCategorical, Integer \n151 \n5 \n1997 \n  Tic-Tac-Toe Endgame\nMultivariate \nClassification \nCategorical \n958 \n9 \n1991 \n  Thyroid Disease\nMultivariate, Domain-Theory \nClassification \nCategorical, Real \n7200 \n21 \n1987 \n  Trains\nMultivariate \nClassification \nCategorical \n10 \n32 \n1994 \n  University\nMultivariate \nClassification \nCategorical, Integer \n285 \n17 \n1988 \n  Congressional Voting Records\nMultivariate \nClassification \nCategorical \n435 \n16 \n1987 \n  Water Treatment Plant\nMultivariate \nClustering \nInteger, Real \n527 \n38 \n1993 \n  Waveform Database Generator (Version 1)\nMultivariate, Data-Generator \nClassification \nReal \n5000 \n21 \n1988 \n  Waveform Database Generator (Version 2)\nMultivariate, Data-Generator \nClassification \nReal \n5000 \n40 \n1988 \n  Wine\nMultivariate \nClassification \nInteger, Real \n178 \n13 \n1991 \n  Yeast\nMultivariate \nClassification \nReal \n1484 \n8 \n1996 \n  Zoo\nMultivariate \nClassification \nCategorical, Integer \n101 \n17 \n1990 \n  Undocumented\n              Twenty Newsgroups\nText \n    20000 \n  1999 \n  Australian Sign Language signs\nMultivariate, Time-Series \nClassification \nCategorical, Real \n6650 \n15 \n1999 \n  Australian Sign Language signs (High Quality)\nMultivariate, Time-Series \nClassification \nReal \n2565 \n22 \n2002 \n  US Census Data (1990)\nMultivariate \nClustering \nCategorical \n2458285 \n68 \n    Census-Income (KDD)\nMultivariate \nClassification \nCategorical, Integer \n299285 \n40 \n2000 \n  Coil 1999 Competition Data\nMultivariate \n  Categorical, Real \n340 \n17 \n1999 \n  Corel Image Features\nMultivariate \n  Real \n68040 \n89 \n1999 \n  E. Coli Genes\nRelational \n        2001 \n  EEG Database\nMultivariate, Time-Series \n  Categorical, Integer, Real \n122 \n4 \n1999 \n  El Nino\nSpatio-temporal \n  Integer, Real \n178080 \n12 \n1999 \n  Entree Chicago Recommendation Data\nTransactional, Sequential \nRecommender-Systems \nCategorical \n50672 \n  2000 \n  CMU Face Images\nImage \nClassification \nInteger \n640 \n  1999 \n  Insurance Company Benchmark (COIL 2000)\nMultivariate \nRegression, Description \nCategorical, Integer \n9000 \n86 \n2000 \n  Internet Usage Data\nMultivariate \n  Categorical, Integer \n10104 \n72 \n1999 \n  IPUMS Census Database\nMultivariate \n  Categorical, Integer \n256932 \n61 \n1999 \n  Japanese Vowels\nMultivariate, Time-Series \nClassification \nReal \n640 \n12 \n    KDD Cup 1998 Data\nMultivariate \nRegression \nCategorical, Integer \n191779 \n481 \n1998 \n  KDD Cup 1999 Data\nMultivariate \nClassification \nCategorical, Integer \n4000000 \n42 \n1999 \n  M. Tuberculosis Genes\nRelational \n        2001 \n  Movie\nMultivariate, Relational \n    10000 \n  1999 \n  MSNBC.com Anonymous Web Data\nSequential \n  Categorical \n989818 \n      NSF Research Award Abstracts 1990-2003\nText \n    129000 \n  2003 \n  Pioneer-1 Mobile Robot Data\nMultivariate, Time-Series \n  Categorical, Real \n    1999 \n  Pseudo Periodic Synthetic Time Series\nUnivariate, Time-Series \n    100000 \n  1999 \n  Reuters-21578 Text Categorization Collection\nText \nClassification \nCategorical \n21578 \n5 \n1997 \n  Robot Execution Failures\nMultivariate, Time-Series \nClassification \nInteger \n463 \n90 \n1999 \n  Synthetic Control Chart Time Series\nTime-Series \nClassification, Clustering \nReal \n600 \n  1999 \n  Syskill and Webert Web Page Ratings\nMultivariate, Text \nClassification \nCategorical \n332 \n5 \n1998 \n  UNIX User Data\nText, Sequential \n            Volcanoes on Venus - JARtool experiment\nImage \nClassification \n          Statlog (Australian Credit Approval)\nMultivariate \nClassification \nCategorical, Integer, Real \n690 \n14 \n    Statlog (German Credit Data)\nMultivariate \nClassification \nCategorical, Integer \n1000 \n20 \n1994 \n  Statlog (Heart)\nMultivariate \nClassification \nCategorical, Real \n270 \n13 \n    Statlog (Landsat Satellite)\nMultivariate \nClassification \nInteger \n6435 \n36 \n1993 \n  Statlog (Image Segmentation)\nMultivariate \nClassification \nReal \n2310 \n19 \n1990 \n  Statlog (Shuttle)\nMultivariate \nClassification \nInteger \n58000 \n9 \n    Statlog (Vehicle Silhouettes)\nMultivariate \nClassification \nInteger \n946 \n18 \n    Connectionist Bench (Nettalk Corpus)\nMultivariate \n  Categorical \n20008 \n4 \n    Connectionist Bench (Sonar, Mines vs. Rocks)\nMultivariate \nClassification \nReal \n208 \n60 \n    Connectionist Bench (Vowel Recognition - Deterding Data)\n  Classification \nReal \n528 \n10 \n    Economic Sanctions\nDomain-Theory \n            Protein Data\n              Cloud\nMultivariate \n  Real \n1024 \n10 \n1989 \n  CalIt2 Building People Counts\nMultivariate, Time-Series \n  Categorical, Integer \n10080 \n4 \n2006 \n  Dodgers Loop Sensor\nMultivariate, Time-Series \n  Categorical, Integer \n50400 \n3 \n2006 \n  Poker Hand\nMultivariate \nClassification \nCategorical, Integer \n1025010 \n11 \n2007 \n  MAGIC Gamma Telescope\nMultivariate \nClassification \nReal \n19020 \n11 \n2007 \n  UJI Pen Characters\nMultivariate, Sequential \nClassification \nInteger \n1364 \n  2007 \n  Mammographic Mass\nMultivariate \nClassification \nInteger \n961 \n6 \n2007 \n  Forest Fires\nMultivariate \nRegression \nReal \n517 \n13 \n2008 \n  Reuters Transcribed Subset\nText \nClassification \n  200 \n  2008 \n  Bag of Words\nText \nClustering \nInteger \n8000000 \n100000 \n2008 \n  Concrete Compressive Strength\nMultivariate \nRegression \nReal \n1030 \n9 \n2007 \n  Hill-Valley\nSequential \nClassification \nReal \n606 \n101 \n2008 \n  Arcene\nMultivariate \nClassification \nReal \n900 \n10000 \n2008 \n  Dexter\nMultivariate \nClassification \nInteger \n2600 \n20000 \n2008 \n  Dorothea\nMultivariate \nClassification \nInteger \n1950 \n100000 \n2008 \n  Gisette\nMultivariate \nClassification \nInteger \n13500 \n5000 \n2008 \n  Madelon\nMultivariate \nClassification \nReal \n4400 \n500 \n2008 \n  Ozone Level Detection\nMultivariate, Sequential, Time-Series \nClassification \nReal \n2536 \n73 \n2008 \n  Abscisic Acid Signaling Network\nMultivariate \nCausal-Discovery \nInteger \n300 \n43 \n2008 \n  Parkinsons\nMultivariate \nClassification \nReal \n197 \n23 \n2008 \n  Character Trajectories\nTime-Series \nClassification, Clustering \nReal \n2858 \n3 \n2008 \n  Blood Transfusion Service Center\nMultivariate \nClassification \nReal \n748 \n5 \n2008 \n  UJI Pen Characters (Version 2)\nMultivariate, Sequential \nClassification \nInteger \n11640 \n  2009 \n  Semeion Handwritten Digit\nMultivariate \nClassification \nInteger \n1593 \n256 \n2008 \n  SECOM\nMultivariate \nClassification, Causal-Discovery \nReal \n1567 \n591 \n2008 \n  Plants\nMultivariate \nClustering \nCategorical \n22632 \n70 \n2008 \n  Libras Movement\nMultivariate, Sequential \nClassification, Clustering \nReal \n360 \n91 \n2009 \n  Concrete Slump Test\nMultivariate \nRegression \nReal \n103 \n10 \n2009 \n  Communities and Crime\nMultivariate \nRegression \nReal \n1994 \n128 \n2009 \n  Acute Inflammations\nMultivariate \nClassification \nCategorical, Integer \n120 \n6 \n2009 \n  Wine Quality\nMultivariate \nClassification, Regression \nReal \n4898 \n12 \n2009 \n  URL Reputation\nMultivariate, Time-Series \nClassification \nInteger, Real \n2396130 \n3231961 \n2009 \n  p53 Mutants\nMultivariate \nClassification \nReal \n16772 \n5409 \n2010 \n  Parkinsons Telemonitoring\nMultivariate \nRegression \nInteger, Real \n5875 \n26 \n2009 \n  Demospongiae\nMultivariate \nClassification \nInteger \n503 \n  2010 \n  Opinosis Opinion ⁄ Review\nText \n    51 \n  2010 \n  Breast Tissue\nMultivariate \nClassification \nReal \n106 \n10 \n2010 \n  Cardiotocography\nMultivariate \nClassification \nReal \n2126 \n23 \n2010 \n  Wall-Following Robot Navigation Data\nMultivariate, Sequential \nClassification \nReal \n5456 \n24 \n2010 \n  Spoken Arabic Digit\nMultivariate, Time-Series \nClassification \nReal \n8800 \n13 \n2010 \n  Localization Data for Person Activity\nUnivariate, Sequential, Time-Series \nClassification \nReal \n164860 \n8 \n2010 \n  AutoUniv\nMultivariate \nClassification \nCategorical, Integer, Real \n    2010 \n  Steel Plates Faults\nMultivariate \nClassification \nInteger, Real \n1941 \n27 \n2010 \n  MiniBooNE particle identification\nMultivariate \nClassification \nReal \n130065 \n50 \n2010 \n  YearPredictionMSD\nMultivariate \nRegression \nReal \n515345 \n90 \n2011 \n  PEMS-SF\nMultivariate, Time-Series \nClassification \nReal \n440 \n138672 \n2011 \n  OpinRank Review Dataset\nText \n        2011 \n  Relative location of CT slices on axial axis\nDomain-Theory \nRegression \nReal \n53500 \n386 \n2011 \n  Online Handwritten Assamese Characters Dataset\nMultivariate, Sequential \nClassification \nInteger \n8235 \n  2011 \n  PubChem Bioassay Data\nMultivariate \nClassification \nInteger, Real \n    2011 \n  Record Linkage Comparison Patterns\nMultivariate \nClassification \nReal \n5749132 \n12 \n2011 \n  Communities and Crime Unnormalized\nMultivariate \nRegression \nReal \n2215 \n147 \n2011 \n  Vertebral Column\nMultivariate \nClassification \nReal \n310 \n6 \n2011 \n  EMG Physical Action Data Set\nTime-Series \nClassification \nReal \n10000 \n8 \n2011 \n  Vicon Physical Action Data Set\nTime-Series \nClassification \nReal \n3000 \n27 \n2011 \n  Amazon Commerce reviews set\nMultivariate, Text, Domain-Theory \nClassification \nReal \n1500 \n10000 \n2011 \n  Amazon Access Samples\nTime-Series, Domain-Theory \nRegression, Clustering, Causal-Discovery \n  30000 \n20000 \n2011 \n  Reuter_50_50\nMultivariate, Text, Domain-Theory \nClassification, Clustering \nReal \n2500 \n10000 \n2011 \n  Farm Ads\nText \nClassification \n  4143 \n54877 \n2011 \n  DBWorld e-mails\nText \nClassification \n  64 \n4702 \n2011 \n  KEGG Metabolic Relation Network (Directed)\nMultivariate, Univariate, Text \nClassification, Regression, Clustering \nInteger, Real \n53414 \n24 \n2011 \n  KEGG Metabolic Reaction Network (Undirected)\nMultivariate, Univariate, Text \nClassification, Regression, Clustering \nInteger, Real \n65554 \n29 \n2011 \n  Bank Marketing\nMultivariate \nClassification \nReal \n45211 \n17 \n2012 \n  YouTube Comedy Slam Preference Data\nText \nClassification \n  1138562 \n3 \n2012 \n  Gas Sensor Array Drift Dataset\nMultivariate \nClassification \nReal \n13910 \n128 \n2012 \n  ILPD (Indian Liver Patient Dataset)\nMultivariate \nClassification \nInteger, Real \n583 \n10 \n2012 \n  OPPORTUNITY Activity Recognition\nMultivariate, Time-Series \nClassification \nReal \n2551 \n242 \n2012 \n  Nomao\nUnivariate \nClassification \nReal \n34465 \n120 \n2012 \n  SMS Spam Collection\nMultivariate, Text, Domain-Theory \nClassification, Clustering \nReal \n5574 \n  2012 \n  Skin Segmentation\nUnivariate \nClassification \nReal \n245057 \n4 \n2012 \n  Planning Relax\nUnivariate \nClassification \nReal \n182 \n13 \n2012 \n  PAMAP2 Physical Activity Monitoring\nMultivariate, Time-Series \nClassification \nReal \n3850505 \n52 \n2012 \n  Restaurant & consumer data\nMultivariate \n    138 \n47 \n2012 \n  CNAE-9\nMultivariate, Text \nClassification \nInteger \n1080 \n857 \n2012 \n  Individual household electric power consumption\nMultivariate, Time-Series \nRegression, Clustering \nReal \n2075259 \n9 \n2012 \n  seeds\nMultivariate \nClassification, Clustering \nReal \n210 \n7 \n2012 \n  Northix\nMultivariate, Univariate, Text \nClassification \nInteger, Real \n115 \n200 \n2012 \n  QtyT40I10D100K\nSequential \n  Integer \n3960456 \n4 \n2012 \n  Legal Case Reports\nText \nClassification \n      2012 \n  Human Activity Recognition Using Smartphones\nMultivariate, Time-Series \nClassification, Clustering \n  10299 \n561 \n2012 \n  One-hundred plant specie

In [8]:
headers=headers[7:]

In [9]:
headers

['  Abalone',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '4177 ',
 '8 ',
 '1995 ',
 '  Adult',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 '  Annealing',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '798 ',
 '38 ',
 '    Anonymous Microsoft Web Data',
 '  Recommender-Systems ',
 'Categorical ',
 '37711 ',
 '294 ',
 '1998 ',
 '  Arrhythmia',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '452 ',
 '279 ',
 '1998 ',
 '  Artificial Characters',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '6000 ',
 '7 ',
 '1992 ',
 '  Audiology (Original)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 '  1987 ',
 '  Audiology (Standardized)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 '69 ',
 '1992 ',
 '  Auto MPG',
 'Multivariate ',
 'Regression ',
 'Categorical, Real ',
 '398 ',
 '8 ',
 '1993 ',
 '  Automobile',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer, Real ',
 '205 ',
 '26 ',
 '1987 ',
 '  Badges',
 'Univariate, Text ',
 'Classification ',
 '  294 ',
 '1 ',
 '1994 ',
 '  Balance Scale',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '625 ',
 '4 ',
 '1994 ',
 '  Balloons',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '16 ',
 '4 ',
 '    Breast Cancer',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '286 ',
 '9 ',
 '1988 ',
 '  Breast Cancer Wisconsin (Original)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '699 ',
 '10 ',
 '1992 ',
 '  Breast Cancer Wisconsin (Prognostic)',
 'Multivariate ',
 'Classification, Regression ',
 'Real ',
 '198 ',
 '34 ',
 '1995 ',
 '  Breast Cancer Wisconsin (Diagnostic)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '569 ',
 '32 ',
 '1995 ',
 '  Pittsburgh Bridges',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '108 ',
 '13 ',
 '1990 ',
 '  Car Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '1728 ',
 '6 ',
 '1997 ',
 '  Census Income',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 '  Chess (King-Rook vs. King-Knight)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical, Integer ',
 '  22 ',
 '1988 ',
 '  Chess (King-Rook vs. King-Pawn)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '3196 ',
 '36 ',
 '1989 ',
 '  Chess (King-Rook vs. King)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '28056 ',
 '6 ',
 '1994 ',
 '  Chess (Domain Theories)',
 'Domain-Theory ',
 '            Bach Chorales',
 'Univariate, Time-Series ',
 '  Categorical, Integer ',
 '100 ',
 '6 ',
 '    Connect-4',
 'Multivariate, Spatial ',
 'Classification ',
 'Categorical ',
 '67557 ',
 '42 ',
 '1995 ',
 '  Credit Approval',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '15 ',
 '    Japanese Credit Screening',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real, Integer ',
 '125 ',
 '  1992 ',
 '  Computer Hardware',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '209 ',
 '9 ',
 '1987 ',
 '  Contraceptive Method Choice',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1473 ',
 '9 ',
 '1997 ',
 '  Covertype',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '581012 ',
 '54 ',
 '1998 ',
 '  Cylinder Bands',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '512 ',
 '39 ',
 '1995 ',
 '  Dermatology',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '366 ',
 '33 ',
 '1998 ',
 '  Diabetes',
 'Multivariate, Time-Series ',
 '  Categorical, Integer ',
 '  20 ',
 '    DGP2 - The Second Data Generation Program',
 'Data-Generator ',
 '  Real ',
 '        Document Understanding',
 '          1994 ',
 '  EBL Domain Theories',
 '              Echocardiogram',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '132 ',
 '12 ',
 '1989 ',
 '  Ecoli',
 'Multivariate ',
 'Classification ',
 'Real ',
 '336 ',
 '8 ',
 '1996 ',
 '  Flags',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '194 ',
 '30 ',
 '1990 ',
 '  Function Finding',
 '  Function-Learning ',
 'Real ',
 '352 ',
 '  1990 ',
 '  Glass Identification',
 'Multivariate ',
 'Classification ',
 'Real ',
 '214 ',
 '10 ',
 '1987 ',
 "  Haberman's Survival",
 'Multivariate ',
 'Classification ',
 'Integer ',
 '306 ',
 '3 ',
 '1999 ',
 '  Hayes-Roth',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '160 ',
 '5 ',
 '1989 ',
 '  Heart Disease',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '303 ',
 '75 ',
 '1988 ',
 '  Hepatitis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '155 ',
 '19 ',
 '1988 ',
 '  Horse Colic',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '368 ',
 '27 ',
 '1989 ',
 '  ICU',
 'Multivariate, Time-Series ',
 '  Real ',
 '        Image Segmentation',
 'Multivariate ',
 'Classification ',
 'Real ',
 '2310 ',
 '19 ',
 '1990 ',
 '  Internet Advertisements',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '3279 ',
 '1558 ',
 '1998 ',
 '  Ionosphere',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '351 ',
 '34 ',
 '1989 ',
 '  Iris',
 'Multivariate ',
 'Classification ',
 'Real ',
 '150 ',
 '4 ',
 '1988 ',
 '  ISOLET',
 'Multivariate ',
 'Classification ',
 'Real ',
 '7797 ',
 '617 ',
 '1994 ',
 '  Kinship',
 'Relational ',
 'Relational-Learning ',
 'Categorical ',
 '104 ',
 '12 ',
 '1990 ',
 '  Labor Relations',
 'Multivariate ',
 '  Categorical, Integer, Real ',
 '57 ',
 '16 ',
 '1988 ',
 '  LED Display Domain',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical ',
 '  7 ',
 '1988 ',
 '  Lenses',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '24 ',
 '4 ',
 '1990 ',
 '  Letter Recognition',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '20000 ',
 '16 ',
 '1991 ',
 '  Liver Disorders',
 'Multivariate ',
 '  Categorical, Integer, Real ',
 '345 ',
 '7 ',
 '1990 ',
 '  Logic Theorist',
 'Domain-Theory ',
 '            Lung Cancer',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '32 ',
 '56 ',
 '1992 ',
 '  Lymphography',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '148 ',
 '18 ',
 '1988 ',
 '  Mechanical Analysis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '209 ',
 '8 ',
 '1990 ',
 '  Meta-data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '528 ',
 '22 ',
 '1996 ',
 '  Mobile Robots',
 'Domain-Theory ',
 '  Categorical, Integer, Real ',
 '    1995 ',
 '  Molecular Biology (Promoter Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '106 ',
 '58 ',
 '1990 ',
 '  Molecular Biology (Protein Secondary Structure)',
 'Sequential ',
 'Classification ',
 'Categorical ',
 '128 ',
 '      Molecular Biology (Splice-junction Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '3190 ',
 '61 ',
 '1992 ',
 "  MONK's Problems",
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '432 ',
 '7 ',
 '1992 ',
 '  Moral Reasoner',
 'Domain-Theory ',
 '    202 ',
 '  1994 ',
 '  Multiple Features',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '2000 ',
 '649 ',
 '    Mushroom',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '8124 ',
 '22 ',
 '1987 ',
 '  Musk (Version 1)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '476 ',
 '168 ',
 '1994 ',
 '  Musk (Version 2)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '6598 ',
 '168 ',
 '1994 ',
 '  Nursery',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '12960 ',
 '8 ',
 '1997 ',
 '  Othello Domain Theory',
 'Domain-Theory ',
 '        1991 ',
 '  Page Blocks Classification',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '5473 ',
 '10 ',
 '1995 ',
 '  Optical Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '5620 ',
 '64 ',
 '1998 ',
 '  Pen-Based Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '10992 ',
 '16 ',
 '1998 ',
 '  Post-Operative Patient',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '90 ',
 '8 ',
 '1993 ',
 '  Primary Tumor',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '339 ',
 '17 ',
 '1988 ',
 '  Prodigy',
 'Domain-Theory ',
 '            Qualitative Structure Activity Relationships',
 'Domain-Theory ',
 '            Quadruped Mammals',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '  72 ',
 '1992 ',
 '  Servo',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '167 ',
 '4 ',
 '1993 ',
 '  Shuttle Landing Control',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '15 ',
 '6 ',
 '1988 ',
 '  Solar Flare',
 'Multivariate ',
 'Regression ',
 'Categorical ',
 '1389 ',
 '10 ',
 '1989 ',
 '  Soybean (Large)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '307 ',
 '35 ',
 '1988 ',
 '  Soybean (Small)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '47 ',
 '35 ',
 '1987 ',
 '  Challenger USA Space Shuttle O-Ring',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '23 ',
 '4 ',
 '1993 ',
 '  Low Resolution Spectrometer',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '531 ',
 '102 ',
 '1988 ',
 '  Spambase',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '4601 ',
 '57 ',
 '1999 ',
 '  SPECT Heart',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '267 ',
 '22 ',
 '2001 ',
 '  SPECTF Heart',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '267 ',
 '44 ',
 '2001 ',
 '  Sponge',
 'Multivariate ',
 'Clustering ',
 'Categorical, Integer ',
 '76 ',
 '45 ',
 '    Statlog Project',
 '          1992 ',
 '  Student Loan Relational',
 'Domain-Theory ',
 '    1000 ',
 '  1993 ',
 '  Teaching Assistant Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '151 ',
 '5 ',
 '1997 ',
 '  Tic-Tac-Toe Endgame',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '958 ',
 '9 ',
 '1991 ',
 '  Thyroid Disease',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real ',
 '7200 ',
 '21 ',
 '1987 ',
 '  Trains',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '10 ',
 '32 ',
 '1994 ',
 '  University',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '285 ',
 '17 ',
 '1988 ',
 '  Congressional Voting Records',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '435 ',
 '16 ',
 '1987 ',
 '  Water Treatment Plant',
 'Multivariate ',
 'Clustering ',
 'Integer, Real ',
 '527 ',
 '38 ',
 '1993 ',
 '  Waveform Database Generator (Version 1)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '21 ',
 '1988 ',
 '  Waveform Database Generator (Version 2)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '40 ',
 '1988 ',
 '  Wine',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '178 ',
 '13 ',
 '1991 ',
 '  Yeast',
 'Multivariate ',
 'Classification ',
 'Real ',
 '1484 ',
 '8 ',
 '1996 ',
 '  Zoo',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '101 ',
 '17 ',
 '1990 ',
 '  Undocumented',
 '              Twenty Newsgroups',
 'Text ',
 '    20000 ',
 '  1999 ',
 '  Australian Sign Language signs',
 'Multivariate, Time-Series ',
 'Classification ',
 'Categorical, Real ',
 '6650 ',
 '15 ',
 '1999 ',
 '  Australian Sign Language signs (High Quality)',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '2565 ',
 '22 ',
 '2002 ',
 '  US Census Data (1990)',
 'Multivariate ',
 'Clustering ',
 'Categorical ',
 '2458285 ',
 '68 ',
 '    Census-Income (KDD)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '299285 ',
 '40 ',
 '2000 ',
 '  Coil 1999 Competition Data',
 'Multivariate ',
 '  Categorical, Real ',
 '340 ',
 '17 ',
 '1999 ',
 '  Corel Image Features',
 'Multivariate ',
 '  Real ',
 '68040 ',
 '89 ',
 '1999 ',
 '  E. Coli Genes',
 'Relational ',
 '        2001 ',
 '  EEG Database',
 'Multivariate, Time-Series ',
 '  Categorical, Integer, Real ',
 '122 ',
 '4 ',
 '1999 ',
 '  El Nino',
 'Spatio-temporal ',
 '  Integer, Real ',
 '178080 ',
 '12 ',
 '1999 ',
 '  Entree Chicago Recommendation Data',
 'Transactional, Sequential ',
 'Recommender-Systems ',
 'Categorical ',
 '50672 ',
 '  2000 ',
 '  CMU Face Images',
 'Image ',
 'Classification ',
 'Integer ',
 '640 ',
 '  1999 ',
 '  Insurance Company Benchmark (COIL 2000)',
 'Multivariate ',
 'Regression, Description ',
 'Categorical, Integer ',
 '9000 ',
 '86 ',
 '2000 ',
 '  Internet Usage Data',
 'Multivariate ',
 '  Categorical, Integer ',
 '10104 ',
 '72 ',
 '1999 ',
 '  IPUMS Census Database',
 'Multivariate ',
 '  Categorical, Integer ',
 '256932 ',
 '61 ',
 '1999 ',
 '  Japanese Vowels',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '640 ',
 '12 ',
 '    KDD Cup 1998 Data',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '191779 ',
 '481 ',
 '1998 ',
 '  KDD Cup 1999 Data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '4000000 ',
 '42 ',
 '1999 ',
 '  M. Tuberculosis Genes',
 'Relational ',
 '        2001 ',
 '  Movie',
 'Multivariate, Relational ',
 '    10000 ',
 '  1999 ',
 '  MSNBC.com Anonymous Web Data',
 'Sequential ',
 '  Categorical ',
 '989818 ',
 '      NSF Research Award Abstracts 1990-2003',
 'Text ',
 '    129000 ',
 '  2003 ',
 '  Pioneer-1 Mobile Robot Data',
 'Multivariate, Time-Series ',
 '  Categorical, Real ',
 '    1999 ',
 '  Pseudo Periodic Synthetic Time Series',
 'Univariate, Time-Series ',
 '    100000 ',
 '  1999 ',
 '  Reuters-21578 Text Categorization Collection',
 'Text ',
 'Classification ',
 'Categorical ',
 '21578 ',
 '5 ',
 '1997 ',
 '  Robot Execution Failures',
 'Multivariate, Time-Series ',
 'Classification ',
 'Integer ',
 '463 ',
 '90 ',
 '1999 ',
 '  Synthetic Control Chart Time Series',
 'Time-Series ',
 'Classification, Clustering ',
 'Real ',
 '600 ',
 '  1999 ',
 '  Syskill and Webert Web Page Ratings',
 'Multivariate, Text ',
 'Classification ',
 'Categorical ',
 '332 ',
 '5 ',
 '1998 ',
 '  UNIX User Data',
 'Text, Sequential ',
 '            Volcanoes on Venus - JARtool experiment',
 'Image ',
 'Classification ',
 '          Statlog (Australian Credit Approval)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '14 ',
 '    Statlog (German Credit Data)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1000 ',
 '20 ',
 '1994 ',
 '  Statlog (Heart)',
 'Multivariate ',
 'Classification ',
 'Categorical, Real ',
 '270 ',
 '13 ',
 '    Statlog (Landsat Satellite)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '6435 ',
 '36 ',
 '1993 ',
 '  Statlog (Image Segmentation)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '2310 ',
 '19 ',
 '1990 ',
 '  Statlog (Shuttle)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '58000 ',
 '9 ',
 '    Statlog (Vehicle Silhouettes)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '946 ',
 '18 ',
 '    Connectionist Bench (Nettalk Corpus)',
 'Multivariate ',
 '  Categorical ',
 '20008 ',
 '4 ',
 '    Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '208 ',
 '60 ',
 '    Connectionist Bench (Vowel Recognition - Deterding Data)',
 '  Classification ',
 'Real ',
 '528 ',
 '10 ',
 '    Economic Sanctions',
 'Domain-Theory ',
 '            Protein Data',
 '              Cloud',
 'Multivariate ',
 '  Real ',
 '1024 ',
 '10 ',
 '1989 ',
 '  CalIt2 Building People Counts',
 'Multivariate, Time-Series ',
 '  Categorical, Integer ',
 '10080 ',
 '4 ',
 '2006 ',
 '  Dodgers Loop Sensor',
 'Multivariate, Time-Series ',
 '  Categorical, Integer ',
 '50400 ',
 '3 ',
 '2006 ',
 '  Poker Hand',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1025010 ',
 '11 ',
 '2007 ',
 '  MAGIC Gamma Telescope',
 'Multivariate ',
 'Classification ',
 'Real ',
 '19020 ',
 '11 ',
 '2007 ',
 '  UJI Pen Characters',
 'Multivariate, Sequential ',
 'Classification ',
 'Integer ',
 '1364 ',
 '  2007 ',
 '  Mammographic Mass',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '961 ',
 '6 ',
 '2007 ',
 '  Forest Fires',
 'Multivariate ',
 'Regression ',
 'Real ',
 '517 ',
 '13 ',
 '2008 ',
 '  Reuters Transcribed Subset',
 'Text ',
 'Classification ',
 '  200 ',
 '  2008 ',
 '  Bag of Words',
 'Text ',
 'Clustering ',
 'Integer ',
 '8000000 ',
 '100000 ',
 '2008 ',
 '  Concrete Compressive Strength',
 'Multivariate ',
 'Regression ',
 'Real ',
 '1030 ',
 '9 ',
 '2007 ',
 '  Hill-Valley',
 'Sequential ',
 'Classification ',
 'Real ',
 '606 ',
 '101 ',
 '2008 ',
 '  Arcene',
 'Multivariate ',
 'Classification ',
 'Real ',
 '900 ',
 '10000 ',
 '2008 ',
 '  Dexter',
 'Multivariate ',
 'Classification ',
 ...]

In [10]:
headers[0::7]

['  Abalone',
 '  Adult',
 '  Annealing',
 '  Recommender-Systems ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical, Integer, Real ',
 '  294 ',
 '625 ',
 '16 ',
 '9 ',
 '10 ',
 '34 ',
 '32 ',
 '13 ',
 '6 ',
 '14 ',
 '1988 ',
 '1989 ',
 '1994 ',
 '6 ',
 '1995 ',
 '    Japanese Credit Screening',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 '          1994 ',
 '12 ',
 '8 ',
 '30 ',
 '  Glass Identification',
 "  Haberman's Survival",
 '  Hayes-Roth',
 '  Heart Disease',
 '  Hepatitis',
 '  Horse Colic',
 '  ICU',
 '2310 ',
 '3279 ',
 '351 ',
 '150 ',
 '7797 ',
 '104 ',
 '16 ',
 '1988 ',
 '1990 ',
 '1991 ',
 '  Logic Theorist',
 '56 ',
 '18 ',
 '8 ',
 '22 ',
 'Sequential, Domain-Theory ',
 'Sequential ',
 'Categorical ',
 'Categorical ',
 '  1994 ',
 '    Mushroom',
 '  Musk (Version 1)',
 '  Musk (Version 2)',
 '  Nursery',
 '  Othello Domain Theory',
 '5473 ',
 '5620 ',
 '10992 ',
 '90 ',
 '339 ',
 '            Quadruped Mammals',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 '  Student Loan Relational',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 '    20000 ',
 '15 ',
 '22 ',
 '68 ',
 '2000 ',
 '  Corel Image Features',
 'Relational ',
 '1999 ',
 '  Entree Chicago Recommendation Data',
 'Image ',
 'Regression, Description ',
 '  Categorical, Integer ',
 '256932 ',
 '640 ',
 '481 ',
 '42 ',
 '    10000 ',
 'Text ',
 '  Pseudo Periodic Synthetic Time Series',
 'Categorical ',
 'Integer ',
 'Real ',
 '332 ',
 'Classification ',
 '    Statlog (German Credit Data)',
 '  Statlog (Heart)',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Classification ',
 '20008 ',
 '60 ',
 'Domain-Theory ',
 '1989 ',
 '  Dodgers Loop Sensor',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Classification ',
 'Regression ',
 'Classification ',
 '8000000 ',
 '1030 ',
 '606 ',
 '900 ',
 '2600 ',
 '1950 ',
 '13500 ',
 '4400 ',
 '2536 ',
 '300 ',
 '197 ',
 '2858 ',
 '748 ',
 '11640 ',
 '256 ',
 '591 ',
 '70 ',
 '91 ',
 '10 ',
 '128 ',
 '6 ',
 '12 ',
 '3231961 ',
 '5409 ',
 '26 ',
 '  2010 ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 '1941 ',
 '130065 ',
 '515345 ',
 '440 ',
 'Domain-Theory ',
 'Multivariate, Sequential ',
 'Classification ',
 '5749132 ',
 '2215 ',
 '310 ',
 '10000 ',
 '3000 ',
 '1500 ',
 '20000 ',
 '10000 ',
 '2011 ',
 '  KEGG Metabolic Relation Network (Directed)',
 '  KEGG Metabolic Reaction Network (Undirected)',
 '  Bank Marketing',
 '  YouTube Comedy Slam Preference Data',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate, Text, Domain-Theory ',
 'Classification ',
 'Classification ',
 'Classification ',
 '    138 ',
 '1080 ',
 '2075259 ',
 '210 ',
 '115 ',
 '4 ',
 'Multivariate, Time-Series ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 '  100 ',
 '9120 ',
 '403 ',
 '111740 ',
 '2013 ',
 "  ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 '  EEG Eye State',
 '  Physicochemical Properties of Protein Tertiary Structure',
 '  seismic-bumps',
 '  banknote authentication',
 '  USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 '  YouTube Multiview Video Games Dataset',
 '  Gas Sensor Array Drift Dataset at Different Concentrations',
 '  Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'Regression ',
 'Classification ',
 'Regression ',
 'Regression ',
 '  Integer, Real ',
 'Integer, Real ',
 '132 ',
 '18 ',
 '2014 ',
 '  LSVT Voice Rehabilitation',
 '  Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Classification ',
 'Real ',
 '  Leaf',
 '  Dresses_Attribute_Sales',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Regression ',
 'Classification ',
 'Integer ',
 '  5665 ',
 '79 ',
 '127 ',
 '1040 ',
 '9900 ',
 '560 ',
 '60021 ',
 '1419 ',
 '  AAAI 2014 Accepted Papers',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Integer, Real ',
 'Real ',
 '  150 ',
 '1059 ',
 '11934 ',
 '27965 ',
 '216 ',
 '120 ',
 '649 ',
 '370 ',
 '4178504 ',
 '221579 ',
 '20 ',
 '49 ',
 '12 ',
 '2015 ',
 '2015 ',
 '2014 ',
 '2015 ',
 'Multivariate ',
 'Multivariate ',
 'Regression, Clustering, Causal-Discovery ',
 'Integer, Real ',
 'Real ',
 'Real ',
 '  637 ',
 '1710671 ',
 '12000 ',
 '10929 ',
 '1080 ',
 '40000 ',
 '43930257 ',
 '230318 ',
 '10500000 ',
 '13197 ',
 '    2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '  Air Quality',
 '  Twin gas sensor arrays',
 '  Gas sensors for home activity monitoring',
 '  Facebook Comment Volume Dataset',
 '  Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 '  Polish companies bankruptcy data',
 '  Activity Recognition system based on Multisensor data fusion (AReM)',
 '  Dota2 Games Results',
 'Multivariate ',
 'Multivariate ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 '153540 ',
 '606 ',
 '1353 ',
 '5 ',
 '13 ',
 '98 ',
 '36 ',
 '69 ',
 '2158859 ',
 '518 ',
 '15 ',
 '179 ',
 '  Stock portfolio performance',
 '  MoCap Hand Postures',
 '  Early biomarkers of Parkinson�s disease based on natural connected speech',
 '  Data for Software Engineering Teamwork Assessment in Education Setting',
 '  PM2.5 Data of Five Chinese Cities',
 '  Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 '  Sales_Transactions_Dataset_Weekly',
 '  Las Vegas Strip',
 'Text ',
 'Integer, Real ',
 '  10546 ',
 '801 ',
 '1540 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '  Z-Alizadeh Sani',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Sequential, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 '  71 ',
 '93239 ',
 '540 ',
 '5 ',
 '15 ',
 '3 ',
 '105 ',
 '25000 ',
 '  2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '  Condition monitoring of hydraulic systems',
 '  Carbon Nanotubes',
 '  Optical Interconnection Network',
 '  Sports articles for objectivity analysis',
 '  Breast Cancer Coimbra',
 '  GNFUV Unmanned Surface Vehicles Sensor Data',
 '  Dishonest Internet users Dataset',
 'Text ',
 'Classification ',
 'Classification ',
 'Integer ',
 '  20000 ',
 '20867 ',
 '    2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '  Online Shoppers Purchasing Intention Dataset',
 '  PMU-UD',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Time-Series ',
 '  1047 ',
 '18 ',
 '7 ',
 '7 ',
 '  Somerville Happiness Survey',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Univariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Classification, Regression ',
 'Clustering ',
 'Classification ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 '  8992 ',
 '1024 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '  Amphibians',
 '  Early stage diabetes risk prediction dataset.',
 'Text ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Real ',
 '  9800 ',
 '4760 ',
 '72 ',
 '  2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '  User Profiling and Abusive Language Detection Dataset',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Clustering ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 '  232 ',
 '52 ',
 '19 ',
 '3 ',
 '14 ',
 '321 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '  Refractive errors',
 '  Shoulder Implant X-Ray Manufacturer Classification',
 '  CLINC150',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Integer ',
 '2020 ',
 '  Codon usage',
 'Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 '  1850 ',
 '11 ',
 '4 ',
 '13 ',
 '55 ',
 '2020 ',
 '  Wheat kernels',
 '  Productivity Prediction of Garment Employees',
 '  Multi-view Brain Networks',
 '  LastFM Asia Social Network',
 'Multivariate, Text ',
 'Classification, Regression, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 '  2021 ',
 '2021 ',
 '2021 ',
 '2021 ',
 '  Secondary Mushroom Dataset',
 '  Power consumption of Tetouan city',
 '  Raisin Dataset',
 '  Steel Industry Energy Consumption Dataset',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 '  597 ',
 '298 ',
 '4 ',
 '11 ',
 '47 ',
 '10 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 'Multivariate, Time-Series ',
 'Univariate ']

In [11]:
len(headers[0::7])

578